// #include "BIS_AddonInfo.hpp"
class CfgPatches
{
	class FlagsNBands
	{
		units[]={};
		weapons[]={};
		requiredVersion=0.1;
		requiredAddons[]=
		{
			"DZ_Characters",
			"DZ_Characters_Backpacks",
			"DZ_Characters_Pants",
			"DZ_Characters_Vests",
			"DZ_Characters_Tops",
			"DZ_Characters_Masks",
			"DZ_Characters_Headgear",
			"DZ_Gear_Camping",
			"DZ_Gear_Containers",
			"DZ_Data"
		};
	};
};
class CfgVehicles
{
	class Clothing;
	class Armband_ColorBase;
	class Armband_108: Armband_ColorBase
	{
		scope=2;
		visibilityModifier=0.94999999;
		color="108";
		hiddenSelectionsTextures[]=
		{
			"MassiveMod\NewClothes\EQClothing\FlagsNBands\data\flag_white_co_108.paa",
			"MassiveMod\NewClothes\EQClothing\FlagsNBands\data\flag_white_co_108.paa",
			"MassiveMod\NewClothes\EQClothing\FlagsNBands\data\flag_white_co_108.paa",
			"MassiveMod\NewClothes\EQClothing\FlagsNBands\data\flag_white_co_108.paa",
			"MassiveMod\NewClothes\EQClothing\FlagsNBands\data\flag_white_co_108.paa",
			"MassiveMod\NewClothes\EQClothing\FlagsNBands\data\flag_white_co_108.paa",
			"MassiveMod\NewClothes\EQClothing\FlagsNBands\data\flag_white_co_108.paa",
			"MassiveMod\NewClothes\EQClothing\FlagsNBands\data\flag_white_co_108.paa",
			"MassiveMod\NewClothes\EQClothing\FlagsNBands\data\flag_white_co_108.paa"
		};
	};
	class Armband_cmf: Armband_ColorBase
	{
		scope=2;
		visibilityModifier=0.94999999;
		color="cmf";
		hiddenSelectionsTextures[]=
		{
			"MassiveMod\NewClothes\EQClothing\FlagsNBands\data\flag_white_co_cmf.paa",
			"MassiveMod\NewClothes\EQClothing\FlagsNBands\data\flag_white_co_cmf.paa",
			"MassiveMod\NewClothes\EQClothing\FlagsNBands\data\flag_white_co_cmf.paa",
			"MassiveMod\NewClothes\EQClothing\FlagsNBands\data\flag_white_co_cmf.paa",
			"MassiveMod\NewClothes\EQClothing\FlagsNBands\data\flag_white_co_cmf.paa",
			"MassiveMod\NewClothes\EQClothing\FlagsNBands\data\flag_white_co_cmf.paa",
			"MassiveMod\NewClothes\EQClothing\FlagsNBands\data\flag_white_co_cmf.paa",
			"MassiveMod\NewClothes\EQClothing\FlagsNBands\data\flag_white_co_cmf.paa",
			"MassiveMod\NewClothes\EQClothing\FlagsNBands\data\flag_white_co_cmf.paa"
		};
	};
	class Armband_ncr: Armband_ColorBase
	{
		scope=2;
		visibilityModifier=0.94999999;
		color="ncr";
		hiddenSelectionsTextures[]=
		{
			"MassiveMod\NewClothes\EQClothing\FlagsNBands\data\flag_white_co_ncr.paa",
			"MassiveMod\NewClothes\EQClothing\FlagsNBands\data\flag_white_co_ncr.paa",
			"MassiveMod\NewClothes\EQClothing\FlagsNBands\data\flag_white_co_ncr.paa",
			"MassiveMod\NewClothes\EQClothing\FlagsNBands\data\flag_white_co_ncr.paa",
			"MassiveMod\NewClothes\EQClothing\FlagsNBands\data\flag_white_co_ncr.paa",
			"MassiveMod\NewClothes\EQClothing\FlagsNBands\data\flag_white_co_ncr.paa",
			"MassiveMod\NewClothes\EQClothing\FlagsNBands\data\flag_white_co_ncr.paa",
			"MassiveMod\NewClothes\EQClothing\FlagsNBands\data\flag_white_co_ncr.paa",
			"MassiveMod\NewClothes\EQClothing\FlagsNBands\data\flag_white_co_ncr.paa"
		};
	};
	class Armband_OOrder: Armband_ColorBase
	{
		scope=2;
		visibilityModifier=0.94999999;
		color="OO";
		hiddenSelectionsTextures[]=
		{
			"MassiveMod\NewClothes\EQClothing\FlagsNBands\data\flag_white_co_OO.paa",
			"MassiveMod\NewClothes\EQClothing\FlagsNBands\data\flag_white_co_OO.paa",
			"MassiveMod\NewClothes\EQClothing\FlagsNBands\data\flag_white_co_OO.paa",
			"MassiveMod\NewClothes\EQClothing\FlagsNBands\data\flag_white_co_OO.paa",
			"MassiveMod\NewClothes\EQClothing\FlagsNBands\data\flag_white_co_OO.paa",
			"MassiveMod\NewClothes\EQClothing\FlagsNBands\data\flag_white_co_OO.paa",
			"MassiveMod\NewClothes\EQClothing\FlagsNBands\data\flag_white_co_OO.paa",
			"MassiveMod\NewClothes\EQClothing\FlagsNBands\data\flag_white_co_OO.paa",
			"MassiveMod\NewClothes\EQClothing\FlagsNBands\data\flag_white_co_OO.paa"
		};
	};
	class Armband_GOK: Armband_ColorBase
	{
		scope=2;
		visibilityModifier=0.94999999;
		color="ghosts";
		hiddenSelectionsTextures[]=
		{
			"MassiveMod\NewClothes\EQClothing\FlagsNBands\data\flag_white_co_ghosts.paa",
			"MassiveMod\NewClothes\EQClothing\FlagsNBands\data\flag_white_co_ghosts.paa",
			"MassiveMod\NewClothes\EQClothing\FlagsNBands\data\flag_white_co_ghosts.paa",
			"MassiveMod\NewClothes\EQClothing\FlagsNBands\data\flag_white_co_ghosts.paa",
			"MassiveMod\NewClothes\EQClothing\FlagsNBands\data\flag_white_co_ghosts.paa",
			"MassiveMod\NewClothes\EQClothing\FlagsNBands\data\flag_white_co_ghosts.paa",
			"MassiveMod\NewClothes\EQClothing\FlagsNBands\data\flag_white_co_ghosts.paa",
			"MassiveMod\NewClothes\EQClothing\FlagsNBands\data\flag_white_co_ghosts.paa",
			"MassiveMod\NewClothes\EQClothing\FlagsNBands\data\flag_white_co_ghosts.paa"
		};
	};
	class Armband_TU: Armband_ColorBase
	{
		scope=2;
		visibilityModifier=0.94999999;
		color="Trade";
		hiddenSelectionsTextures[]=
		{
			"MassiveMod\NewClothes\EQClothing\FlagsNBands\data\flag_white_co_TU.paa",
			"MassiveMod\NewClothes\EQClothing\FlagsNBands\data\flag_white_co_TU.paa",
			"MassiveMod\NewClothes\EQClothing\FlagsNBands\data\flag_white_co_TU.paa",
			"MassiveMod\NewClothes\EQClothing\FlagsNBands\data\flag_white_co_TU.paa",
			"MassiveMod\NewClothes\EQClothing\FlagsNBands\data\flag_white_co_TU.paa",
			"MassiveMod\NewClothes\EQClothing\FlagsNBands\data\flag_white_co_TU.paa",
			"MassiveMod\NewClothes\EQClothing\FlagsNBands\data\flag_white_co_TU.paa",
			"MassiveMod\NewClothes\EQClothing\FlagsNBands\data\flag_white_co_TU.paa",
			"MassiveMod\NewClothes\EQClothing\FlagsNBands\data\flag_white_co_TU.paa"
		};
	};
	class Armband_Medic: Armband_ColorBase
	{
		scope=2;
		visibilityModifier=0.94999999;
		color="medic";
		hiddenSelectionsTextures[]=
		{
			"MassiveMod\NewClothes\EQClothing\FlagsNBands\data\flag_white_co_medic_armband_large.paa",
			"MassiveMod\NewClothes\EQClothing\FlagsNBands\data\flag_white_co_medic_armband_large.paa",
			"MassiveMod\NewClothes\EQClothing\FlagsNBands\data\flag_white_co_medic_armband_large.paa",
			"MassiveMod\NewClothes\EQClothing\FlagsNBands\data\flag_white_co_medic_armband_large.paa",
			"MassiveMod\NewClothes\EQClothing\FlagsNBands\data\flag_white_co_medic_armband_large.paa",
			"MassiveMod\NewClothes\EQClothing\FlagsNBands\data\flag_white_co_medic_armband_large.paa",
			"MassiveMod\NewClothes\EQClothing\FlagsNBands\data\flag_white_co_medic_armband_large.paa",
			"MassiveMod\NewClothes\EQClothing\FlagsNBands\data\flag_white_co_medic_armband_large.paa",
			"MassiveMod\NewClothes\EQClothing\FlagsNBands\data\flag_white_co_medic_armband_large.paa"
		};
	};
	class Armband_Medic_small: Armband_ColorBase
	{
		scope=2;
		visibilityModifier=0.94999999;
		color="medic2";
		hiddenSelectionsTextures[]=
		{
			"MassiveMod\NewClothes\EQClothing\FlagsNBands\data\flag_white_co_medic_armband_small.paa",
			"MassiveMod\NewClothes\EQClothing\FlagsNBands\data\flag_white_co_medic_armband_small.paa",
			"MassiveMod\NewClothes\EQClothing\FlagsNBands\data\flag_white_co_medic_armband_small.paa",
			"MassiveMod\NewClothes\EQClothing\FlagsNBands\data\flag_white_co_medic_armband_small.paa",
			"MassiveMod\NewClothes\EQClothing\FlagsNBands\data\flag_white_co_medic_armband_small.paa",
			"MassiveMod\NewClothes\EQClothing\FlagsNBands\data\flag_white_co_medic_armband_small.paa",
			"MassiveMod\NewClothes\EQClothing\FlagsNBands\data\flag_white_co_medic_armband_small.paa",
			"MassiveMod\NewClothes\EQClothing\FlagsNBands\data\flag_white_co_medic_armband_small.paa",
			"MassiveMod\NewClothes\EQClothing\FlagsNBands\data\flag_white_co_medic_armband_small.paa"
		};
	};
	class Armband_imperium: Armband_ColorBase
	{
		scope=2;
		visibilityModifier=0.94999999;
		color="newimpB";
		hiddenSelectionsTextures[]=
		{
			"MassiveMod\NewClothes\EQClothing\FlagsNBands\data\impnewb_flag_white_co.paa",
			"MassiveMod\NewClothes\EQClothing\FlagsNBands\data\impnewb_flag_white_co.paa",
			"MassiveMod\NewClothes\EQClothing\FlagsNBands\data\impnewb_flag_white_co.paa",
			"MassiveMod\NewClothes\EQClothing\FlagsNBands\data\impnewb_flag_white_co.paa",
			"MassiveMod\NewClothes\EQClothing\FlagsNBands\data\impnewb_flag_white_co.paa",
			"MassiveMod\NewClothes\EQClothing\FlagsNBands\data\impnewb_flag_white_co.paa",
			"MassiveMod\NewClothes\EQClothing\FlagsNBands\data\impnewb_flag_white_co.paa",
			"MassiveMod\NewClothes\EQClothing\FlagsNBands\data\impnewb_flag_white_co.paa",
			"MassiveMod\NewClothes\EQClothing\FlagsNBands\data\impnewb_flag_white_co.paa"
		};
	};
	class Armband_imperiumR: Armband_ColorBase
	{
		scope=2;
		visibilityModifier=0.94999999;
		color="newimpR";
		hiddenSelectionsTextures[]=
		{
			"MassiveMod\NewClothes\EQClothing\FlagsNBands\data\Imperium_red.paa",
			"MassiveMod\NewClothes\EQClothing\FlagsNBands\data\Imperium_red.paa",
			"MassiveMod\NewClothes\EQClothing\FlagsNBands\data\Imperium_red.paa",
			"MassiveMod\NewClothes\EQClothing\FlagsNBands\data\Imperium_red.paa",
			"MassiveMod\NewClothes\EQClothing\FlagsNBands\data\Imperium_red.paa",
			"MassiveMod\NewClothes\EQClothing\FlagsNBands\data\Imperium_red.paa",
			"MassiveMod\NewClothes\EQClothing\FlagsNBands\data\Imperium_red.paa",
			"MassiveMod\NewClothes\EQClothing\FlagsNBands\data\Imperium_red.paa",
			"MassiveMod\NewClothes\EQClothing\FlagsNBands\data\Imperium_red.paa"
		};
	};
	class Armband_druzhina: Armband_ColorBase
	{
		scope=2;
		visibilityModifier=0.94999999;
		color="druzhina";
		hiddenSelectionsTextures[]=
		{
			"MassiveMod\NewClothes\EQClothing\FlagsNBands\data\flag_white_co_druzhina.paa",
			"MassiveMod\NewClothes\EQClothing\FlagsNBands\data\flag_white_co_druzhina.paa",
			"MassiveMod\NewClothes\EQClothing\FlagsNBands\data\flag_white_co_druzhina.paa",
			"MassiveMod\NewClothes\EQClothing\FlagsNBands\data\flag_white_co_druzhina.paa",
			"MassiveMod\NewClothes\EQClothing\FlagsNBands\data\flag_white_co_druzhina.paa",
			"MassiveMod\NewClothes\EQClothing\FlagsNBands\data\flag_white_co_druzhina.paa",
			"MassiveMod\NewClothes\EQClothing\FlagsNBands\data\flag_white_co_druzhina.paa",
			"MassiveMod\NewClothes\EQClothing\FlagsNBands\data\flag_white_co_druzhina.paa",
			"MassiveMod\NewClothes\EQClothing\FlagsNBands\data\flag_white_co_druzhina.paa"
		};
	};
	class Armband_end: Armband_ColorBase
	{
		scope=2;
		visibilityModifier=0.94999999;
		color="end";
		hiddenSelectionsTextures[]=
		{
			"MassiveMod\NewClothes\EQClothing\FlagsNBands\data\end_flag_3.paa",
			"MassiveMod\NewClothes\EQClothing\FlagsNBands\data\end_flag_3.paa",
			"MassiveMod\NewClothes\EQClothing\FlagsNBands\data\end_flag_3.paa",
			"MassiveMod\NewClothes\EQClothing\FlagsNBands\data\end_flag_3.paa",
			"MassiveMod\NewClothes\EQClothing\FlagsNBands\data\end_flag_3.paa",
			"MassiveMod\NewClothes\EQClothing\FlagsNBands\data\end_flag_3.paa",
			"MassiveMod\NewClothes\EQClothing\FlagsNBands\data\end_flag_3.paa",
			"MassiveMod\NewClothes\EQClothing\FlagsNBands\data\end_flag_3.paa",
			"MassiveMod\NewClothes\EQClothing\FlagsNBands\data\end_flag_3.paa"
		};
	};
	class Armband_Northern_Republic: Armband_ColorBase
	{
		scope=2;
		visibilityModifier=0.94999999;
		color="North Rep";
		hiddenSelectionsTextures[]=
		{
			"MassiveMod\NewClothes\EQClothing\FlagsNBands\data\flag_Northern_Republic.paa",
			"MassiveMod\NewClothes\EQClothing\FlagsNBands\data\flag_Northern_Republic.paa",
			"MassiveMod\NewClothes\EQClothing\FlagsNBands\data\flag_Northern_Republic.paa",
			"MassiveMod\NewClothes\EQClothing\FlagsNBands\data\flag_Northern_Republic.paa",
			"MassiveMod\NewClothes\EQClothing\FlagsNBands\data\flag_Northern_Republic.paa",
			"MassiveMod\NewClothes\EQClothing\FlagsNBands\data\flag_Northern_Republic.paa",
			"MassiveMod\NewClothes\EQClothing\FlagsNBands\data\flag_Northern_Republic.paa",
			"MassiveMod\NewClothes\EQClothing\FlagsNBands\data\flag_Northern_Republic.paa",
			"MassiveMod\NewClothes\EQClothing\FlagsNBands\data\flag_Northern_Republic.paa"
		};
	};
	class Armband_ZenComm: Armband_ColorBase
	{
		scope=2;
		visibilityModifier=0.94999999;
		color="ZenComm";
		hiddenSelectionsTextures[]=
		{
			"MassiveMod\NewClothes\EQClothing\FlagsNBands\data\armband_ZenComm.paa",
			"MassiveMod\NewClothes\EQClothing\FlagsNBands\data\armband_ZenComm.paa",
			"MassiveMod\NewClothes\EQClothing\FlagsNBands\data\armband_ZenComm.paa",
			"MassiveMod\NewClothes\EQClothing\FlagsNBands\data\armband_ZenComm.paa",
			"MassiveMod\NewClothes\EQClothing\FlagsNBands\data\armband_ZenComm.paa",
			"MassiveMod\NewClothes\EQClothing\FlagsNBands\data\armband_ZenComm.paa",
			"MassiveMod\NewClothes\EQClothing\FlagsNBands\data\armband_ZenComm.paa",
			"MassiveMod\NewClothes\EQClothing\FlagsNBands\data\armband_ZenComm.paa",
			"MassiveMod\NewClothes\EQClothing\FlagsNBands\data\armband_ZenComm.paa"
		};
	};
	class Armband_Eclipse: Armband_ColorBase
	{
		scope=2;
		visibilityModifier=0.94999999;
		color="Eclipse";
		hiddenSelectionsTextures[]=
		{
			"MassiveMod\NewClothes\EQClothing\FlagsNBands\data\Eclipse_flag.paa",
			"MassiveMod\NewClothes\EQClothing\FlagsNBands\data\Eclipse_flag.paa",
			"MassiveMod\NewClothes\EQClothing\FlagsNBands\data\Eclipse_flag.paa",
			"MassiveMod\NewClothes\EQClothing\FlagsNBands\data\Eclipse_flag.paa",
			"MassiveMod\NewClothes\EQClothing\FlagsNBands\data\Eclipse_flag.paa",
			"MassiveMod\NewClothes\EQClothing\FlagsNBands\data\Eclipse_flag.paa",
			"MassiveMod\NewClothes\EQClothing\FlagsNBands\data\Eclipse_flag.paa",
			"MassiveMod\NewClothes\EQClothing\FlagsNBands\data\Eclipse_flag.paa",
			"MassiveMod\NewClothes\EQClothing\FlagsNBands\data\Eclipse_flag.paa"
		};
	};
	class flag_base;
	class flag_108: flag_base
	{
		scope=2;
		visibilityModifier=0.94999999;
		color="108";
		hiddenSelectionsTextures[]=
		{
			"MassiveMod\NewClothes\EQClothing\FlagsNBands\data\flag_white_co_108.paa",
			"MassiveMod\NewClothes\EQClothing\FlagsNBands\data\flag_white_co_108.paa",
			"MassiveMod\NewClothes\EQClothing\FlagsNBands\data\flag_white_co_108.paa",
			"MassiveMod\NewClothes\EQClothing\FlagsNBands\data\flag_white_co_108.paa",
			"MassiveMod\NewClothes\EQClothing\FlagsNBands\data\flag_white_co_108.paa",
			"MassiveMod\NewClothes\EQClothing\FlagsNBands\data\flag_white_co_108.paa",
			"MassiveMod\NewClothes\EQClothing\FlagsNBands\data\flag_white_co_108.paa",
			"MassiveMod\NewClothes\EQClothing\FlagsNBands\data\flag_white_co_108.paa",
			"MassiveMod\NewClothes\EQClothing\FlagsNBands\data\flag_white_co_108.paa"
		};
	};
	class flag_cmf: flag_base
	{
		scope=2;
		visibilityModifier=0.94999999;
		color="cmf";
		hiddenSelectionsTextures[]=
		{
			"MassiveMod\NewClothes\EQClothing\FlagsNBands\data\flag_white_co_cmf.paa",
			"MassiveMod\NewClothes\EQClothing\FlagsNBands\data\flag_white_co_cmf.paa",
			"MassiveMod\NewClothes\EQClothing\FlagsNBands\data\flag_white_co_cmf.paa",
			"MassiveMod\NewClothes\EQClothing\FlagsNBands\data\flag_white_co_cmf.paa",
			"MassiveMod\NewClothes\EQClothing\FlagsNBands\data\flag_white_co_cmf.paa",
			"MassiveMod\NewClothes\EQClothing\FlagsNBands\data\flag_white_co_cmf.paa",
			"MassiveMod\NewClothes\EQClothing\FlagsNBands\data\flag_white_co_cmf.paa",
			"MassiveMod\NewClothes\EQClothing\FlagsNBands\data\flag_white_co_cmf.paa",
			"MassiveMod\NewClothes\EQClothing\FlagsNBands\data\flag_white_co_cmf.paa"
		};
	};
	class flag_ncr: flag_base
	{
		scope=2;
		visibilityModifier=0.94999999;
		color="ncr";
		hiddenSelectionsTextures[]=
		{
			"MassiveMod\NewClothes\EQClothing\FlagsNBands\data\flag_white_co_ncr.paa",
			"MassiveMod\NewClothes\EQClothing\FlagsNBands\data\flag_white_co_ncr.paa",
			"MassiveMod\NewClothes\EQClothing\FlagsNBands\data\flag_white_co_ncr.paa",
			"MassiveMod\NewClothes\EQClothing\FlagsNBands\data\flag_white_co_ncr.paa",
			"MassiveMod\NewClothes\EQClothing\FlagsNBands\data\flag_white_co_ncr.paa",
			"MassiveMod\NewClothes\EQClothing\FlagsNBands\data\flag_white_co_ncr.paa",
			"MassiveMod\NewClothes\EQClothing\FlagsNBands\data\flag_white_co_ncr.paa",
			"MassiveMod\NewClothes\EQClothing\FlagsNBands\data\flag_white_co_ncr.paa",
			"MassiveMod\NewClothes\EQClothing\FlagsNBands\data\flag_white_co_ncr.paa"
		};
	};
	class flag_OOrder: flag_base
	{
		scope=2;
		visibilityModifier=0.94999999;
		color="OO";
		hiddenSelectionsTextures[]=
		{
			"MassiveMod\NewClothes\EQClothing\FlagsNBands\data\flag_white_co_OO.paa",
			"MassiveMod\NewClothes\EQClothing\FlagsNBands\data\flag_white_co_OO.paa",
			"MassiveMod\NewClothes\EQClothing\FlagsNBands\data\flag_white_co_OO.paa",
			"MassiveMod\NewClothes\EQClothing\FlagsNBands\data\flag_white_co_OO.paa",
			"MassiveMod\NewClothes\EQClothing\FlagsNBands\data\flag_white_co_OO.paa",
			"MassiveMod\NewClothes\EQClothing\FlagsNBands\data\flag_white_co_OO.paa",
			"MassiveMod\NewClothes\EQClothing\FlagsNBands\data\flag_white_co_OO.paa",
			"MassiveMod\NewClothes\EQClothing\FlagsNBands\data\flag_white_co_OO.paa",
			"MassiveMod\NewClothes\EQClothing\FlagsNBands\data\flag_white_co_OO.paa"
		};
	};
	class flag_GOK: flag_base
	{
		scope=2;
		visibilityModifier=0.94999999;
		color="ghosts";
		hiddenSelectionsTextures[]=
		{
			"MassiveMod\NewClothes\EQClothing\FlagsNBands\data\flag_white_co_ghosts.paa",
			"MassiveMod\NewClothes\EQClothing\FlagsNBands\data\flag_white_co_ghosts.paa",
			"MassiveMod\NewClothes\EQClothing\FlagsNBands\data\flag_white_co_ghosts.paa",
			"MassiveMod\NewClothes\EQClothing\FlagsNBands\data\flag_white_co_ghosts.paa",
			"MassiveMod\NewClothes\EQClothing\FlagsNBands\data\flag_white_co_ghosts.paa",
			"MassiveMod\NewClothes\EQClothing\FlagsNBands\data\flag_white_co_ghosts.paa",
			"MassiveMod\NewClothes\EQClothing\FlagsNBands\data\flag_white_co_ghosts.paa",
			"MassiveMod\NewClothes\EQClothing\FlagsNBands\data\flag_white_co_ghosts.paa",
			"MassiveMod\NewClothes\EQClothing\FlagsNBands\data\flag_white_co_ghosts.paa"
		};
	};
	class flag_TU: flag_base
	{
		scope=2;
		visibilityModifier=0.94999999;
		color="Trade";
		hiddenSelectionsTextures[]=
		{
			"MassiveMod\NewClothes\EQClothing\FlagsNBands\data\flag_white_co_TU.paa",
			"MassiveMod\NewClothes\EQClothing\FlagsNBands\data\flag_white_co_TU.paa",
			"MassiveMod\NewClothes\EQClothing\FlagsNBands\data\flag_white_co_TU.paa",
			"MassiveMod\NewClothes\EQClothing\FlagsNBands\data\flag_white_co_TU.paa",
			"MassiveMod\NewClothes\EQClothing\FlagsNBands\data\flag_white_co_TU.paa",
			"MassiveMod\NewClothes\EQClothing\FlagsNBands\data\flag_white_co_TU.paa",
			"MassiveMod\NewClothes\EQClothing\FlagsNBands\data\flag_white_co_TU.paa",
			"MassiveMod\NewClothes\EQClothing\FlagsNBands\data\flag_white_co_TU.paa",
			"MassiveMod\NewClothes\EQClothing\FlagsNBands\data\flag_white_co_TU.paa"
		};
	};
	class flag_Medic: flag_base
	{
		scope=2;
		visibilityModifier=0.94999999;
		color="medic";
		hiddenSelectionsTextures[]=
		{
			"MassiveMod\NewClothes\EQClothing\FlagsNBands\data\flag_white_co_medic_armband_large.paa",
			"MassiveMod\NewClothes\EQClothing\FlagsNBands\data\flag_white_co_medic_armband_large.paa",
			"MassiveMod\NewClothes\EQClothing\FlagsNBands\data\flag_white_co_medic_armband_large.paa",
			"MassiveMod\NewClothes\EQClothing\FlagsNBands\data\flag_white_co_medic_armband_large.paa",
			"MassiveMod\NewClothes\EQClothing\FlagsNBands\data\flag_white_co_medic_armband_large.paa",
			"MassiveMod\NewClothes\EQClothing\FlagsNBands\data\flag_white_co_medic_armband_large.paa",
			"MassiveMod\NewClothes\EQClothing\FlagsNBands\data\flag_white_co_medic_armband_large.paa",
			"MassiveMod\NewClothes\EQClothing\FlagsNBands\data\flag_white_co_medic_armband_large.paa",
			"MassiveMod\NewClothes\EQClothing\FlagsNBands\data\flag_white_co_medic_armband_large.paa"
		};
	};
	class flag_Medic_small: flag_base
	{
		scope=2;
		visibilityModifier=0.94999999;
		color="medic2";
		hiddenSelectionsTextures[]=
		{
			"MassiveMod\NewClothes\EQClothing\FlagsNBands\data\flag_white_co_medic_armband_small.paa",
			"MassiveMod\NewClothes\EQClothing\FlagsNBands\data\flag_white_co_medic_armband_small.paa",
			"MassiveMod\NewClothes\EQClothing\FlagsNBands\data\flag_white_co_medic_armband_small.paa",
			"MassiveMod\NewClothes\EQClothing\FlagsNBands\data\flag_white_co_medic_armband_small.paa",
			"MassiveMod\NewClothes\EQClothing\FlagsNBands\data\flag_white_co_medic_armband_small.paa",
			"MassiveMod\NewClothes\EQClothing\FlagsNBands\data\flag_white_co_medic_armband_small.paa",
			"MassiveMod\NewClothes\EQClothing\FlagsNBands\data\flag_white_co_medic_armband_small.paa",
			"MassiveMod\NewClothes\EQClothing\FlagsNBands\data\flag_white_co_medic_armband_small.paa",
			"MassiveMod\NewClothes\EQClothing\FlagsNBands\data\flag_white_co_medic_armband_small.paa"
		};
	};
	class flag_imperium: flag_base
	{
		scope=2;
		visibilityModifier=0.94999999;
		color="newimpR";
		hiddenSelectionsTextures[]=
		{
			"MassiveMod\NewClothes\EQClothing\FlagsNBands\data\Imperium_red.paa",
			"MassiveMod\NewClothes\EQClothing\FlagsNBands\data\Imperium_red.paa",
			"MassiveMod\NewClothes\EQClothing\FlagsNBands\data\Imperium_red.paa",
			"MassiveMod\NewClothes\EQClothing\FlagsNBands\data\Imperium_red.paa",
			"MassiveMod\NewClothes\EQClothing\FlagsNBands\data\Imperium_red.paa",
			"MassiveMod\NewClothes\EQClothing\FlagsNBands\data\Imperium_red.paa",
			"MassiveMod\NewClothes\EQClothing\FlagsNBands\data\Imperium_red.paa",
			"MassiveMod\NewClothes\EQClothing\FlagsNBands\data\Imperium_red.paa",
			"MassiveMod\NewClothes\EQClothing\FlagsNBands\data\Imperium_red.paa"
		};
	};
	class flag_Druzhina: flag_base
	{
		scope=2;
		visibilityModifier=0.94999999;
		color="druzhina";
		hiddenSelectionsTextures[]=
		{
			"MassiveMod\NewClothes\EQClothing\FlagsNBands\data\flag_white_co_druzhina.paa",
			"MassiveMod\NewClothes\EQClothing\FlagsNBands\data\flag_white_co_druzhina.paa",
			"MassiveMod\NewClothes\EQClothing\FlagsNBands\data\flag_white_co_druzhina.paa",
			"MassiveMod\NewClothes\EQClothing\FlagsNBands\data\flag_white_co_druzhina.paa",
			"MassiveMod\NewClothes\EQClothing\FlagsNBands\data\flag_white_co_druzhina.paa",
			"MassiveMod\NewClothes\EQClothing\FlagsNBands\data\flag_white_co_druzhina.paa",
			"MassiveMod\NewClothes\EQClothing\FlagsNBands\data\flag_white_co_druzhina.paa",
			"MassiveMod\NewClothes\EQClothing\FlagsNBands\data\flag_white_co_druzhina.paa",
			"MassiveMod\NewClothes\EQClothing\FlagsNBands\data\flag_white_co_druzhina.paa"
		};
	};
	class flag_end: flag_base
	{
		scope=2;
		visibilityModifier=0.94999999;
		color="end";
		hiddenSelectionsTextures[]=
		{
			"MassiveMod\NewClothes\EQClothing\FlagsNBands\data\end_flag_3.paa",
			"MassiveMod\NewClothes\EQClothing\FlagsNBands\data\end_flag_3.paa",
			"MassiveMod\NewClothes\EQClothing\FlagsNBands\data\end_flag_3.paa",
			"MassiveMod\NewClothes\EQClothing\FlagsNBands\data\end_flag_3.paa",
			"MassiveMod\NewClothes\EQClothing\FlagsNBands\data\end_flag_3.paa",
			"MassiveMod\NewClothes\EQClothing\FlagsNBands\data\end_flag_3.paa",
			"MassiveMod\NewClothes\EQClothing\FlagsNBands\data\end_flag_3.paa",
			"MassiveMod\NewClothes\EQClothing\FlagsNBands\data\end_flag_3.paa",
			"MassiveMod\NewClothes\EQClothing\FlagsNBands\data\end_flag_3.paa"
		};
	};
	class flag_Northern_Republic: flag_base
	{
		scope=2;
		visibilityModifier=0.94999999;
		color="North Rep";
		hiddenSelectionsTextures[]=
		{
			"MassiveMod\NewClothes\EQClothing\FlagsNBands\data\flag_Northern_Republic.paa",
			"MassiveMod\NewClothes\EQClothing\FlagsNBands\data\flag_Northern_Republic.paa",
			"MassiveMod\NewClothes\EQClothing\FlagsNBands\data\flag_Northern_Republic.paa",
			"MassiveMod\NewClothes\EQClothing\FlagsNBands\data\flag_Northern_Republic.paa",
			"MassiveMod\NewClothes\EQClothing\FlagsNBands\data\flag_Northern_Republic.paa",
			"MassiveMod\NewClothes\EQClothing\FlagsNBands\data\flag_Northern_Republic.paa",
			"MassiveMod\NewClothes\EQClothing\FlagsNBands\data\flag_Northern_Republic.paa",
			"MassiveMod\NewClothes\EQClothing\FlagsNBands\data\flag_Northern_Republic.paa",
			"MassiveMod\NewClothes\EQClothing\FlagsNBands\data\flag_Northern_Republic.paa"
		};
	};
	class flag_ZenComm: flag_base
	{
		scope=2;
		visibilityModifier=0.94999999;
		color="ZenComm";
		hiddenSelectionsTextures[]=
		{
			"MassiveMod\NewClothes\EQClothing\FlagsNBands\data\flag_ZenComm.paa",
			"MassiveMod\NewClothes\EQClothing\FlagsNBands\data\flag_ZenComm.paa",
			"MassiveMod\NewClothes\EQClothing\FlagsNBands\data\flag_ZenComm.paa",
			"MassiveMod\NewClothes\EQClothing\FlagsNBands\data\flag_ZenComm.paa",
			"MassiveMod\NewClothes\EQClothing\FlagsNBands\data\flag_ZenComm.paa",
			"MassiveMod\NewClothes\EQClothing\FlagsNBands\data\flag_ZenComm.paa",
			"MassiveMod\NewClothes\EQClothing\FlagsNBands\data\flag_ZenComm.paa",
			"MassiveMod\NewClothes\EQClothing\FlagsNBands\data\flag_ZenComm.paa",
			"MassiveMod\NewClothes\EQClothing\FlagsNBands\data\flag_ZenComm.paa"
		};
	};
	class flag_Eclipse: flag_base
	{
		scope=2;
		visibilityModifier=0.94999999;
		color="Eclipse";
		hiddenSelectionsTextures[]=
		{
			"MassiveMod\NewClothes\EQClothing\FlagsNBands\data\Eclipse_flag.paa",
			"MassiveMod\NewClothes\EQClothing\FlagsNBands\data\Eclipse_flag.paa",
			"MassiveMod\NewClothes\EQClothing\FlagsNBands\data\Eclipse_flag.paa",
			"MassiveMod\NewClothes\EQClothing\FlagsNBands\data\Eclipse_flag.paa",
			"MassiveMod\NewClothes\EQClothing\FlagsNBands\data\Eclipse_flag.paa",
			"MassiveMod\NewClothes\EQClothing\FlagsNBands\data\Eclipse_flag.paa",
			"MassiveMod\NewClothes\EQClothing\FlagsNBands\data\Eclipse_flag.paa",
			"MassiveMod\NewClothes\EQClothing\FlagsNBands\data\Eclipse_flag.paa",
			"MassiveMod\NewClothes\EQClothing\FlagsNBands\data\Eclipse_flag.paa"
		};
	};
};