// #include "BIS_AddonInfo.hpp"
class CfgPatches
{
	class FlagsNBands
	{
		units[]={};
		weapons[]={};
		requiredVersion=0.1;
		requiredAddons[]=
		{
			"DZ_Characters",
			"DZ_Characters_Backpacks",
			"DZ_Characters_Pants",
			"DZ_Characters_Vests",
			"DZ_Characters_Tops",
			"DZ_Characters_Masks",
			"DZ_Characters_Headgear",
			"DZ_Gear_Camping",
			"DZ_Gear_Containers",
			"DZ_Data"
		};
	};
};
class CfgVehicles
{
	class Clothing;
	class Armband_ColorBase;
	class Armband_108: Armband_ColorBase
	{
		scope=2;
		visibilityModifier=0.94999999;
		color="108";
		hiddenSelectionsTextures[]=
		{
			"MassiveMod\NewClothes\EQClothing\FlagsNBands\data\flag_white_co_108.paa",
			"MassiveMod\NewClothes\EQClothing\FlagsNBands\data\flag_white_co_108.paa",
			"MassiveMod\NewClothes\EQClothing\FlagsNBands\data\flag_white_co_108.paa",
			"MassiveMod\NewClothes\EQClothing\FlagsNBands\data\flag_white_co_108.paa",
			"MassiveMod\NewClothes\EQClothing\FlagsNBands\data\flag_white_co_108.paa",
			"MassiveMod\NewClothes\EQClothing\FlagsNBands\data\flag_white_co_108.paa",
			"MassiveMod\NewClothes\EQClothing\FlagsNBands\data\flag_white_co_108.paa",
			"MassiveMod\NewClothes\EQClothing\FlagsNBands\data\flag_white_co_108.paa",
			"MassiveMod\NewClothes\EQClothing\FlagsNBands\data\flag_white_co_108.paa"
		};
	};
	class Armband_cmf: Armband_ColorBase
	{
		scope=2;
		visibilityModifier=0.94999999;
		color="cmf";
		hiddenSelectionsTextures[]=
		{
			"MassiveMod\NewClothes\EQClothing\FlagsNBands\data\flag_white_co_cmf.paa",
			"MassiveMod\NewClothes\EQClothing\FlagsNBands\data\flag_white_co_cmf.paa",
			"MassiveMod\NewClothes\EQClothing\FlagsNBands\data\flag_white_co_cmf.paa",
			"MassiveMod\NewClothes\EQClothing\FlagsNBands\data\flag_white_co_cmf.paa",
			"MassiveMod\NewClothes\EQClothing\FlagsNBands\data\flag_white_co_cmf.paa",
			"MassiveMod\NewClothes\EQClothing\FlagsNBands\data\flag_white_co_cmf.paa",
			"MassiveMod\NewClothes\EQClothing\FlagsNBands\data\flag_white_co_cmf.paa",
			"MassiveMod\NewClothes\EQClothing\FlagsNBands\data\flag_white_co_cmf.paa",
			"MassiveMod\NewClothes\EQClothing\FlagsNBands\data\flag_white_co_cmf.paa"
		};
	};
	class Armband_ncr: Armband_ColorBase
	{
		scope=2;
		visibilityModifier=0.94999999;
		color="ncr";
		hiddenSelectionsTextures[]=
		{
			"MassiveMod\NewClothes\EQClothing\FlagsNBands\data\flag_white_co_ncr.paa",
			"MassiveMod\NewClothes\EQClothing\FlagsNBands\data\flag_white_co_ncr.paa",
			"MassiveMod\NewClothes\EQClothing\FlagsNBands\data\flag_white_co_ncr.paa",
			"MassiveMod\NewClothes\EQClothing\FlagsNBands\data\flag_white_co_ncr.paa",
			"MassiveMod\NewClothes\EQClothing\FlagsNBands\data\flag_white_co_ncr.paa",
			"MassiveMod\NewClothes\EQClothing\FlagsNBands\data\flag_white_co_ncr.paa",
			"MassiveMod\NewClothes\EQClothing\FlagsNBands\data\flag_white_co_ncr.paa",
			"MassiveMod\NewClothes\EQClothing\FlagsNBands\data\flag_white_co_ncr.paa",
			"MassiveMod\NewClothes\EQClothing\FlagsNBands\data\flag_white_co_ncr.paa"
		};
	};
	class Armband_OOrder: Armband_ColorBase
	{
		scope=2;
		visibilityModifier=0.94999999;
		color="OO";
		hiddenSelectionsTextures[]=
		{
			"MassiveMod\NewClothes\EQClothing\FlagsNBands\data\flag_white_co_OO.paa",
			"MassiveMod\NewClothes\EQClothing\FlagsNBands\data\flag_white_co_OO.paa",
			"MassiveMod\NewClothes\EQClothing\FlagsNBands\data\flag_white_co_OO.paa",
			"MassiveMod\NewClothes\EQClothing\FlagsNBands\data\flag_white_co_OO.paa",
			"MassiveMod\NewClothes\EQClothing\FlagsNBands\data\flag_white_co_OO.paa",
			"MassiveMod\NewClothes\EQClothing\FlagsNBands\data\flag_white_co_OO.paa",
			"MassiveMod\NewClothes\EQClothing\FlagsNBands\data\flag_white_co_OO.paa",
			"MassiveMod\NewClothes\EQClothing\FlagsNBands\data\flag_white_co_OO.paa",
			"MassiveMod\NewClothes\EQClothing\FlagsNBands\data\flag_white_co_OO.paa"
		};
	};
	class Armband_GOK: Armband_ColorBase
	{
		scope=2;
		visibilityModifier=0.94999999;
		color="ghosts";
		hiddenSelectionsTextures[]=
		{
			"MassiveMod\NewClothes\EQClothing\FlagsNBands\data\flag_white_co_ghosts.paa",
			"MassiveMod\NewClothes\EQClothing\FlagsNBands\data\flag_white_co_ghosts.paa",
			"MassiveMod\NewClothes\EQClothing\FlagsNBands\data\flag_white_co_ghosts.paa",
			"MassiveMod\NewClothes\EQClothing\FlagsNBands\data\flag_white_co_ghosts.paa",
			"MassiveMod\NewClothes\EQClothing\FlagsNBands\data\flag_white_co_ghosts.paa",
			"MassiveMod\NewClothes\EQClothing\FlagsNBands\data\flag_white_co_ghosts.paa",
			"MassiveMod\NewClothes\EQClothing\FlagsNBands\data\flag_white_co_ghosts.paa",
			"MassiveMod\NewClothes\EQClothing\FlagsNBands\data\flag_white_co_ghosts.paa",
			"MassiveMod\NewClothes\EQClothing\FlagsNBands\data\flag_white_co_ghosts.paa"
		};
	};
	class Armband_TU: Armband_ColorBase
	{
		scope=2;
		visibilityModifier=0.94999999;
		color="Trade";
		hiddenSelectionsTextures[]=
		{
			"MassiveMod\NewClothes\EQClothing\FlagsNBands\data\Armband_TU_NEW.paa",
			"MassiveMod\NewClothes\EQClothing\FlagsNBands\data\Armband_TU_NEW.paa",
			"MassiveMod\NewClothes\EQClothing\FlagsNBands\data\Armband_TU_NEW.paa",
			"MassiveMod\NewClothes\EQClothing\FlagsNBands\data\Armband_TU_NEW.paa",
			"MassiveMod\NewClothes\EQClothing\FlagsNBands\data\Armband_TU_NEW.paa",
			"MassiveMod\NewClothes\EQClothing\FlagsNBands\data\Armband_TU_NEW.paa",
			"MassiveMod\NewClothes\EQClothing\FlagsNBands\data\Armband_TU_NEW.paa",
			"MassiveMod\NewClothes\EQClothing\FlagsNBands\data\Armband_TU_NEW.paa",
			"MassiveMod\NewClothes\EQClothing\FlagsNBands\data\Armband_TU_NEW.paa"
		};
	};
	class Armband_Medic: Armband_ColorBase
	{
		scope=2;
		visibilityModifier=0.94999999;
		color="medic";
		hiddenSelectionsTextures[]=
		{
			"MassiveMod\NewClothes\EQClothing\FlagsNBands\data\flag_white_co_medic_armband_large.paa",
			"MassiveMod\NewClothes\EQClothing\FlagsNBands\data\flag_white_co_medic_armband_large.paa",
			"MassiveMod\NewClothes\EQClothing\FlagsNBands\data\flag_white_co_medic_armband_large.paa",
			"MassiveMod\NewClothes\EQClothing\FlagsNBands\data\flag_white_co_medic_armband_large.paa",
			"MassiveMod\NewClothes\EQClothing\FlagsNBands\data\flag_white_co_medic_armband_large.paa",
			"MassiveMod\NewClothes\EQClothing\FlagsNBands\data\flag_white_co_medic_armband_large.paa",
			"MassiveMod\NewClothes\EQClothing\FlagsNBands\data\flag_white_co_medic_armband_large.paa",
			"MassiveMod\NewClothes\EQClothing\FlagsNBands\data\flag_white_co_medic_armband_large.paa",
			"MassiveMod\NewClothes\EQClothing\FlagsNBands\data\flag_white_co_medic_armband_large.paa"
		};
	};
	class Armband_Medic_small: Armband_ColorBase
	{
		scope=2;
		visibilityModifier=0.94999999;
		color="medic2";
		hiddenSelectionsTextures[]=
		{
			"MassiveMod\NewClothes\EQClothing\FlagsNBands\data\flag_white_co_medic_armband_small.paa",
			"MassiveMod\NewClothes\EQClothing\FlagsNBands\data\flag_white_co_medic_armband_small.paa",
			"MassiveMod\NewClothes\EQClothing\FlagsNBands\data\flag_white_co_medic_armband_small.paa",
			"MassiveMod\NewClothes\EQClothing\FlagsNBands\data\flag_white_co_medic_armband_small.paa",
			"MassiveMod\NewClothes\EQClothing\FlagsNBands\data\flag_white_co_medic_armband_small.paa",
			"MassiveMod\NewClothes\EQClothing\FlagsNBands\data\flag_white_co_medic_armband_small.paa",
			"MassiveMod\NewClothes\EQClothing\FlagsNBands\data\flag_white_co_medic_armband_small.paa",
			"MassiveMod\NewClothes\EQClothing\FlagsNBands\data\flag_white_co_medic_armband_small.paa",
			"MassiveMod\NewClothes\EQClothing\FlagsNBands\data\flag_white_co_medic_armband_small.paa"
		};
	};
	class Armband_imperium: Armband_ColorBase
	{
		scope=2;
		visibilityModifier=0.94999999;
		color="newimpB";
		hiddenSelectionsTextures[]=
		{
			"MassiveMod\NewClothes\EQClothing\FlagsNBands\data\impnewb_flag_white_co.paa",
			"MassiveMod\NewClothes\EQClothing\FlagsNBands\data\impnewb_flag_white_co.paa",
			"MassiveMod\NewClothes\EQClothing\FlagsNBands\data\impnewb_flag_white_co.paa",
			"MassiveMod\NewClothes\EQClothing\FlagsNBands\data\impnewb_flag_white_co.paa",
			"MassiveMod\NewClothes\EQClothing\FlagsNBands\data\impnewb_flag_white_co.paa",
			"MassiveMod\NewClothes\EQClothing\FlagsNBands\data\impnewb_flag_white_co.paa",
			"MassiveMod\NewClothes\EQClothing\FlagsNBands\data\impnewb_flag_white_co.paa",
			"MassiveMod\NewClothes\EQClothing\FlagsNBands\data\impnewb_flag_white_co.paa",
			"MassiveMod\NewClothes\EQClothing\FlagsNBands\data\impnewb_flag_white_co.paa"
		};
	};
	class Armband_imperiumR: Armband_ColorBase
	{
		scope=2;
		visibilityModifier=0.94999999;
		color="newimpR";
		hiddenSelectionsTextures[]=
		{
			"MassiveMod\NewClothes\EQClothing\FlagsNBands\data\Imperium_red.paa",
			"MassiveMod\NewClothes\EQClothing\FlagsNBands\data\Imperium_red.paa",
			"MassiveMod\NewClothes\EQClothing\FlagsNBands\data\Imperium_red.paa",
			"MassiveMod\NewClothes\EQClothing\FlagsNBands\data\Imperium_red.paa",
			"MassiveMod\NewClothes\EQClothing\FlagsNBands\data\Imperium_red.paa",
			"MassiveMod\NewClothes\EQClothing\FlagsNBands\data\Imperium_red.paa",
			"MassiveMod\NewClothes\EQClothing\FlagsNBands\data\Imperium_red.paa",
			"MassiveMod\NewClothes\EQClothing\FlagsNBands\data\Imperium_red.paa",
			"MassiveMod\NewClothes\EQClothing\FlagsNBands\data\Imperium_red.paa"
		};
	};
	class Armband_druzhina: Armband_ColorBase
	{
		scope=2;
		visibilityModifier=0.94999999;
		color="druzhina";
		hiddenSelectionsTextures[]=
		{
			"MassiveMod\NewClothes\EQClothing\FlagsNBands\data\flag_white_co_druzhina.paa",
			"MassiveMod\NewClothes\EQClothing\FlagsNBands\data\flag_white_co_druzhina.paa",
			"MassiveMod\NewClothes\EQClothing\FlagsNBands\data\flag_white_co_druzhina.paa",
			"MassiveMod\NewClothes\EQClothing\FlagsNBands\data\flag_white_co_druzhina.paa",
			"MassiveMod\NewClothes\EQClothing\FlagsNBands\data\flag_white_co_druzhina.paa",
			"MassiveMod\NewClothes\EQClothing\FlagsNBands\data\flag_white_co_druzhina.paa",
			"MassiveMod\NewClothes\EQClothing\FlagsNBands\data\flag_white_co_druzhina.paa",
			"MassiveMod\NewClothes\EQClothing\FlagsNBands\data\flag_white_co_druzhina.paa",
			"MassiveMod\NewClothes\EQClothing\FlagsNBands\data\flag_white_co_druzhina.paa"
		};
	};
	class Armband_end: Armband_ColorBase
	{
		scope=2;
		visibilityModifier=0.94999999;
		color="end";
		hiddenSelectionsTextures[]=
		{
			"MassiveMod\NewClothes\EQClothing\FlagsNBands\data\flag_END2.paa",
			"MassiveMod\NewClothes\EQClothing\FlagsNBands\data\flag_END2.paa",
			"MassiveMod\NewClothes\EQClothing\FlagsNBands\data\flag_END2.paa",
			"MassiveMod\NewClothes\EQClothing\FlagsNBands\data\flag_END2.paa",
			"MassiveMod\NewClothes\EQClothing\FlagsNBands\data\flag_END2.paa",
			"MassiveMod\NewClothes\EQClothing\FlagsNBands\data\flag_END2.paa",
			"MassiveMod\NewClothes\EQClothing\FlagsNBands\data\flag_END2.paa",
			"MassiveMod\NewClothes\EQClothing\FlagsNBands\data\flag_END2.paa",
			"MassiveMod\NewClothes\EQClothing\FlagsNBands\data\flag_END2.paa"
		};
	};
	class Armband_Northern_Republic: Armband_ColorBase
	{
		scope=2;
		visibilityModifier=0.94999999;
		color="North Rep";
		hiddenSelectionsTextures[]=
		{
			"MassiveMod\NewClothes\EQClothing\FlagsNBands\data\flag_Northern_Republic.paa",
			"MassiveMod\NewClothes\EQClothing\FlagsNBands\data\flag_Northern_Republic.paa",
			"MassiveMod\NewClothes\EQClothing\FlagsNBands\data\flag_Northern_Republic.paa",
			"MassiveMod\NewClothes\EQClothing\FlagsNBands\data\flag_Northern_Republic.paa",
			"MassiveMod\NewClothes\EQClothing\FlagsNBands\data\flag_Northern_Republic.paa",
			"MassiveMod\NewClothes\EQClothing\FlagsNBands\data\flag_Northern_Republic.paa",
			"MassiveMod\NewClothes\EQClothing\FlagsNBands\data\flag_Northern_Republic.paa",
			"MassiveMod\NewClothes\EQClothing\FlagsNBands\data\flag_Northern_Republic.paa",
			"MassiveMod\NewClothes\EQClothing\FlagsNBands\data\flag_Northern_Republic.paa"
		};
	};
	class Armband_ZenComm: Armband_ColorBase
	{
		scope=2;
		visibilityModifier=0.94999999;
		color="ZenComm";
		hiddenSelectionsTextures[]=
		{
			"MassiveMod\NewClothes\EQClothing\FlagsNBands\data\armband_ZenComm.paa",
			"MassiveMod\NewClothes\EQClothing\FlagsNBands\data\armband_ZenComm.paa",
			"MassiveMod\NewClothes\EQClothing\FlagsNBands\data\armband_ZenComm.paa",
			"MassiveMod\NewClothes\EQClothing\FlagsNBands\data\armband_ZenComm.paa",
			"MassiveMod\NewClothes\EQClothing\FlagsNBands\data\armband_ZenComm.paa",
			"MassiveMod\NewClothes\EQClothing\FlagsNBands\data\armband_ZenComm.paa",
			"MassiveMod\NewClothes\EQClothing\FlagsNBands\data\armband_ZenComm.paa",
			"MassiveMod\NewClothes\EQClothing\FlagsNBands\data\armband_ZenComm.paa",
			"MassiveMod\NewClothes\EQClothing\FlagsNBands\data\armband_ZenComm.paa"
		};
	};
	class Armband_Eclipse: Armband_ColorBase
	{
		scope=2;
		visibilityModifier=0.94999999;
		color="Eclipse";
		hiddenSelectionsTextures[]=
		{
			"MassiveMod\NewClothes\EQClothing\FlagsNBands\data\Eclipse_flag.paa",
			"MassiveMod\NewClothes\EQClothing\FlagsNBands\data\Eclipse_flag.paa",
			"MassiveMod\NewClothes\EQClothing\FlagsNBands\data\Eclipse_flag.paa",
			"MassiveMod\NewClothes\EQClothing\FlagsNBands\data\Eclipse_flag.paa",
			"MassiveMod\NewClothes\EQClothing\FlagsNBands\data\Eclipse_flag.paa",
			"MassiveMod\NewClothes\EQClothing\FlagsNBands\data\Eclipse_flag.paa",
			"MassiveMod\NewClothes\EQClothing\FlagsNBands\data\Eclipse_flag.paa",
			"MassiveMod\NewClothes\EQClothing\FlagsNBands\data\Eclipse_flag.paa",
			"MassiveMod\NewClothes\EQClothing\FlagsNBands\data\Eclipse_flag.paa"
		};
	};
	class Armband_Blackwater: Armband_ColorBase
	{
		scope=2;
		visibilityModifier=0.94999999;
		color="Eclipse";
		hiddenSelectionsTextures[]=
		{
			"MassiveMod\NewClothes\EQClothing\FlagsNBands\data\Blackwater_armband.paa",
			"MassiveMod\NewClothes\EQClothing\FlagsNBands\data\Blackwater_armband.paa",
			"MassiveMod\NewClothes\EQClothing\FlagsNBands\data\Blackwater_armband.paa",
			"MassiveMod\NewClothes\EQClothing\FlagsNBands\data\Blackwater_armband.paa",
			"MassiveMod\NewClothes\EQClothing\FlagsNBands\data\Blackwater_armband.paa",
			"MassiveMod\NewClothes\EQClothing\FlagsNBands\data\Blackwater_armband.paa",
			"MassiveMod\NewClothes\EQClothing\FlagsNBands\data\Blackwater_armband.paa",
			"MassiveMod\NewClothes\EQClothing\FlagsNBands\data\Blackwater_armband.paa",
			"MassiveMod\NewClothes\EQClothing\FlagsNBands\data\Blackwater_armband.paa"
		};
	};
	class Armband_Jackals: Armband_ColorBase
	{
		scope=2;
		visibilityModifier=0.94999999;
		color="Jackals";
		hiddenSelectionsTextures[]=
		{
			"MassiveMod\NewClothes\EQClothing\FlagsNBands\data\Jackals_armband.paa",
			"MassiveMod\NewClothes\EQClothing\FlagsNBands\data\Jackals_armband.paa",
			"MassiveMod\NewClothes\EQClothing\FlagsNBands\data\Jackals_armband.paa",
			"MassiveMod\NewClothes\EQClothing\FlagsNBands\data\Jackals_armband.paa",
			"MassiveMod\NewClothes\EQClothing\FlagsNBands\data\Jackals_armband.paa",
			"MassiveMod\NewClothes\EQClothing\FlagsNBands\data\Jackals_armband.paa",
			"MassiveMod\NewClothes\EQClothing\FlagsNBands\data\Jackals_armband.paa",
			"MassiveMod\NewClothes\EQClothing\FlagsNBands\data\Jackals_armband.paa",
			"MassiveMod\NewClothes\EQClothing\FlagsNBands\data\Jackals_armband.paa"
		};
	};
	class Armband_KJ: Armband_ColorBase
	{
		scope=2;
		visibilityModifier=0.94999999;
		color="Pickle";
		hiddenSelectionsTextures[]=
		{
			"MassiveMod\NewClothes\EQClothing\FlagsNBands\data\flag_KJ.paa",
			"MassiveMod\NewClothes\EQClothing\FlagsNBands\data\flag_KJ.paa",
			"MassiveMod\NewClothes\EQClothing\FlagsNBands\data\flag_KJ.paa",
			"MassiveMod\NewClothes\EQClothing\FlagsNBands\data\flag_KJ.paa",
			"MassiveMod\NewClothes\EQClothing\FlagsNBands\data\flag_KJ.paa",
			"MassiveMod\NewClothes\EQClothing\FlagsNBands\data\flag_KJ.paa",
			"MassiveMod\NewClothes\EQClothing\FlagsNBands\data\flag_KJ.paa",
			"MassiveMod\NewClothes\EQClothing\FlagsNBands\data\flag_KJ.paa",
			"MassiveMod\NewClothes\EQClothing\FlagsNBands\data\flag_KJ.paa"
		};
	};
	class Armband_BPirate: Armband_ColorBase
	{
		scope=2;
		visibilityModifier=0.94999999;
		color="BPirate";
		hiddenSelectionsTextures[]=
		{
			"MassiveMod\NewClothes\EQClothing\FlagsNBands\data\flag_BPirate.paa",
			"MassiveMod\NewClothes\EQClothing\FlagsNBands\data\flag_BPirate.paa",
			"MassiveMod\NewClothes\EQClothing\FlagsNBands\data\flag_BPirate.paa",
			"MassiveMod\NewClothes\EQClothing\FlagsNBands\data\flag_BPirate.paa",
			"MassiveMod\NewClothes\EQClothing\FlagsNBands\data\flag_BPirate.paa",
			"MassiveMod\NewClothes\EQClothing\FlagsNBands\data\flag_BPirate.paa",
			"MassiveMod\NewClothes\EQClothing\FlagsNBands\data\flag_BPirate.paa",
			"MassiveMod\NewClothes\EQClothing\FlagsNBands\data\flag_BPirate.paa",
			"MassiveMod\NewClothes\EQClothing\FlagsNBands\data\flag_BPirate.paa"
		};
	};
	class Armband_RoughRiders: Armband_ColorBase
	{
		scope=2;
		visibilityModifier=0.94999999;
		color="RoughRiders";
		hiddenSelectionsTextures[]=
		{
			"MassiveMod\NewClothes\EQClothing\FlagsNBands\data\Rough_Riders_flag.paa",
			"MassiveMod\NewClothes\EQClothing\FlagsNBands\data\Rough_Riders_flag.paa",
			"MassiveMod\NewClothes\EQClothing\FlagsNBands\data\Rough_Riders_flag.paa",
			"MassiveMod\NewClothes\EQClothing\FlagsNBands\data\Rough_Riders_flag.paa",
			"MassiveMod\NewClothes\EQClothing\FlagsNBands\data\Rough_Riders_flag.paa",
			"MassiveMod\NewClothes\EQClothing\FlagsNBands\data\Rough_Riders_flag.paa",
			"MassiveMod\NewClothes\EQClothing\FlagsNBands\data\Rough_Riders_flag.paa",
			"MassiveMod\NewClothes\EQClothing\FlagsNBands\data\Rough_Riders_flag.paa",
			"MassiveMod\NewClothes\EQClothing\FlagsNBands\data\Rough_Riders_flag.paa"
		};
	};
	class Armband_NRPS: Armband_ColorBase
	{
		scope=2;
		visibilityModifier=0.94999999;
		color="Purple Sage";
		hiddenSelectionsTextures[]=
		{
			"MassiveMod\NewClothes\EQClothing\FlagsNBands\data\NRPS_flag.paa",
			"MassiveMod\NewClothes\EQClothing\FlagsNBands\data\NRPS_flag.paa",
			"MassiveMod\NewClothes\EQClothing\FlagsNBands\data\NRPS_flag.paa",
			"MassiveMod\NewClothes\EQClothing\FlagsNBands\data\NRPS_flag.paa",
			"MassiveMod\NewClothes\EQClothing\FlagsNBands\data\NRPS_flag.paa",
			"MassiveMod\NewClothes\EQClothing\FlagsNBands\data\NRPS_flag.paa",
			"MassiveMod\NewClothes\EQClothing\FlagsNBands\data\NRPS_flag.paa",
			"MassiveMod\NewClothes\EQClothing\FlagsNBands\data\NRPS_flag.paa",
			"MassiveMod\NewClothes\EQClothing\FlagsNBands\data\NRPS_flag.paa"
		};
	};
	class Armband_Renegades: Armband_ColorBase
	{
		scope=2;
		visibilityModifier=0.94999999;
		color="Renegades";
		hiddenSelectionsTextures[]=
		{
			"MassiveMod\NewClothes\EQClothing\FlagsNBands\data\Renegades_flag.paa",
			"MassiveMod\NewClothes\EQClothing\FlagsNBands\data\Renegades_flag.paa",
			"MassiveMod\NewClothes\EQClothing\FlagsNBands\data\Renegades_flag.paa",
			"MassiveMod\NewClothes\EQClothing\FlagsNBands\data\Renegades_flag.paa",
			"MassiveMod\NewClothes\EQClothing\FlagsNBands\data\Renegades_flag.paa",
			"MassiveMod\NewClothes\EQClothing\FlagsNBands\data\Renegades_flag.paa",
			"MassiveMod\NewClothes\EQClothing\FlagsNBands\data\Renegades_flag.paa",
			"MassiveMod\NewClothes\EQClothing\FlagsNBands\data\Renegades_flag.paa",
			"MassiveMod\NewClothes\EQClothing\FlagsNBands\data\Renegades_flag.paa"
		};
	};
	class Armband_SCCollective: Armband_ColorBase
	{
		scope=2;
		visibilityModifier=0.94999999;
		color="Collective";
		hiddenSelectionsTextures[]=
		{
			"MassiveMod\NewClothes\EQClothing\FlagsNBands\data\SCCollective_flag.paa",
			"MassiveMod\NewClothes\EQClothing\FlagsNBands\data\SCCollective_flag.paa",
			"MassiveMod\NewClothes\EQClothing\FlagsNBands\data\SCCollective_flag.paa",
			"MassiveMod\NewClothes\EQClothing\FlagsNBands\data\SCCollective_flag.paa",
			"MassiveMod\NewClothes\EQClothing\FlagsNBands\data\SCCollective_flag.paa",
			"MassiveMod\NewClothes\EQClothing\FlagsNBands\data\SCCollective_flag.paa",
			"MassiveMod\NewClothes\EQClothing\FlagsNBands\data\SCCollective_flag.paa",
			"MassiveMod\NewClothes\EQClothing\FlagsNBands\data\SCCollective_flag.paa",
			"MassiveMod\NewClothes\EQClothing\FlagsNBands\data\SCCollective_flag.paa"
		};
	};
	class Armband_Afirma: Armband_ColorBase
	{
		scope=2;
		visibilityModifier=0.94999999;
		color="Afirma";
		hiddenSelectionsTextures[]=
		{
			"MassiveMod\NewClothes\EQClothing\FlagsNBands\data\afirma_flag.paa",
			"MassiveMod\NewClothes\EQClothing\FlagsNBands\data\afirma_flag.paa",
			"MassiveMod\NewClothes\EQClothing\FlagsNBands\data\afirma_flag.paa",
			"MassiveMod\NewClothes\EQClothing\FlagsNBands\data\afirma_flag.paa",
			"MassiveMod\NewClothes\EQClothing\FlagsNBands\data\afirma_flag.paa",
			"MassiveMod\NewClothes\EQClothing\FlagsNBands\data\afirma_flag.paa",
			"MassiveMod\NewClothes\EQClothing\FlagsNBands\data\afirma_flag.paa",
			"MassiveMod\NewClothes\EQClothing\FlagsNBands\data\afirma_flag.paa",
			"MassiveMod\NewClothes\EQClothing\FlagsNBands\data\afirma_flag.paa"
		};
	};
	class Armband_GOK2: Armband_ColorBase
	{
		scope=2;
		visibilityModifier=0.94999999;
		color="GOK New";
		hiddenSelectionsTextures[]=
		{
			"MassiveMod\NewClothes\EQClothing\FlagsNBands\data\GoK2_flag.paa",
			"MassiveMod\NewClothes\EQClothing\FlagsNBands\data\GoK2_flag.paa",
			"MassiveMod\NewClothes\EQClothing\FlagsNBands\data\GoK2_flag.paa",
			"MassiveMod\NewClothes\EQClothing\FlagsNBands\data\GoK2_flag.paa",
			"MassiveMod\NewClothes\EQClothing\FlagsNBands\data\GoK2_flag.paa",
			"MassiveMod\NewClothes\EQClothing\FlagsNBands\data\GoK2_flag.paa",
			"MassiveMod\NewClothes\EQClothing\FlagsNBands\data\GoK2_flag.paa",
			"MassiveMod\NewClothes\EQClothing\FlagsNBands\data\GoK2_flag.paa",
			"MassiveMod\NewClothes\EQClothing\FlagsNBands\data\GoK2_flag.paa"
		};
	};
	class Armband_JusticeLeague: Armband_ColorBase
	{
		scope=2;
		visibilityModifier=0.94999999;
		color="Justice League";
		hiddenSelectionsTextures[]=
		{
			"MassiveMod\NewClothes\EQClothing\FlagsNBands\data\JusticeLeague_flag.paa",
			"MassiveMod\NewClothes\EQClothing\FlagsNBands\data\JusticeLeague_flag.paa",
			"MassiveMod\NewClothes\EQClothing\FlagsNBands\data\JusticeLeague_flag.paa",
			"MassiveMod\NewClothes\EQClothing\FlagsNBands\data\JusticeLeague_flag.paa",
			"MassiveMod\NewClothes\EQClothing\FlagsNBands\data\JusticeLeague_flag.paa",
			"MassiveMod\NewClothes\EQClothing\FlagsNBands\data\JusticeLeague_flag.paa",
			"MassiveMod\NewClothes\EQClothing\FlagsNBands\data\JusticeLeague_flag.paa",
			"MassiveMod\NewClothes\EQClothing\FlagsNBands\data\JusticeLeague_flag.paa",
			"MassiveMod\NewClothes\EQClothing\FlagsNBands\data\JusticeLeague_flag.paa"
		};
	};
	class Armband_Mogilevka: Armband_ColorBase
	{
		scope=2;
		visibilityModifier=0.94999999;
		color="Mogilevka";
		hiddenSelectionsTextures[]=
		{
			"MassiveMod\NewClothes\EQClothing\FlagsNBands\data\Mogilevka_flag.paa",
			"MassiveMod\NewClothes\EQClothing\FlagsNBands\data\Mogilevka_flag.paa",
			"MassiveMod\NewClothes\EQClothing\FlagsNBands\data\Mogilevka_flag.paa",
			"MassiveMod\NewClothes\EQClothing\FlagsNBands\data\Mogilevka_flag.paa",
			"MassiveMod\NewClothes\EQClothing\FlagsNBands\data\Mogilevka_flag.paa",
			"MassiveMod\NewClothes\EQClothing\FlagsNBands\data\Mogilevka_flag.paa",
			"MassiveMod\NewClothes\EQClothing\FlagsNBands\data\Mogilevka_flag.paa",
			"MassiveMod\NewClothes\EQClothing\FlagsNBands\data\Mogilevka_flag.paa",
			"MassiveMod\NewClothes\EQClothing\FlagsNBands\data\Mogilevka_flag.paa"
		};
	};
	class Armband_Blackwater2: Armband_ColorBase
	{
		scope=2;
		visibilityModifier=0.94999999;
		color="Blackwater";
		hiddenSelectionsTextures[]=
		{
			"MassiveMod\NewClothes\EQClothing\FlagsNBands\data\Blackwater_armband2.paa",
			"MassiveMod\NewClothes\EQClothing\FlagsNBands\data\Blackwater_armband2.paa",
			"MassiveMod\NewClothes\EQClothing\FlagsNBands\data\Blackwater_armband2.paa",
			"MassiveMod\NewClothes\EQClothing\FlagsNBands\data\Blackwater_armband2.paa",
			"MassiveMod\NewClothes\EQClothing\FlagsNBands\data\Blackwater_armband2.paa",
			"MassiveMod\NewClothes\EQClothing\FlagsNBands\data\Blackwater_armband2.paa",
			"MassiveMod\NewClothes\EQClothing\FlagsNBands\data\Blackwater_armband2.paa",
			"MassiveMod\NewClothes\EQClothing\FlagsNBands\data\Blackwater_armband2.paa",
			"MassiveMod\NewClothes\EQClothing\FlagsNBands\data\Blackwater_armband2.paa"
		};
	};
	class Armband_TBT: Armband_ColorBase
	{
		scope=2;
		visibilityModifier=0.94999999;
		color="TBT";
		hiddenSelectionsTextures[]=
		{
			"MassiveMod\NewClothes\EQClothing\FlagsNBands\data\Flag_TBT.paa",
			"MassiveMod\NewClothes\EQClothing\FlagsNBands\data\Flag_TBT.paa",
			"MassiveMod\NewClothes\EQClothing\FlagsNBands\data\Flag_TBT.paa",
			"MassiveMod\NewClothes\EQClothing\FlagsNBands\data\Flag_TBT.paa",
			"MassiveMod\NewClothes\EQClothing\FlagsNBands\data\Flag_TBT.paa",
			"MassiveMod\NewClothes\EQClothing\FlagsNBands\data\Flag_TBT.paa",
			"MassiveMod\NewClothes\EQClothing\FlagsNBands\data\Flag_TBT.paa",
			"MassiveMod\NewClothes\EQClothing\FlagsNBands\data\Flag_TBT.paa",
			"MassiveMod\NewClothes\EQClothing\FlagsNBands\data\Flag_TBT.paa"
		};
	};
	class Armband_BRMercenarious: Armband_ColorBase
	{
		scope=2;
		visibilityModifier=0.94999999;
		color="BRMercenarious";
		hiddenSelectionsTextures[]=
		{
			"MassiveMod\NewClothes\EQClothing\FlagsNBands\data\Flag_BRMercenarious.paa",
			"MassiveMod\NewClothes\EQClothing\FlagsNBands\data\Flag_BRMercenarious.paa",
			"MassiveMod\NewClothes\EQClothing\FlagsNBands\data\Flag_BRMercenarious.paa",
			"MassiveMod\NewClothes\EQClothing\FlagsNBands\data\Flag_BRMercenarious.paa",
			"MassiveMod\NewClothes\EQClothing\FlagsNBands\data\Flag_BRMercenarious.paa",
			"MassiveMod\NewClothes\EQClothing\FlagsNBands\data\Flag_BRMercenarious.paa",
			"MassiveMod\NewClothes\EQClothing\FlagsNBands\data\Flag_BRMercenarious.paa",
			"MassiveMod\NewClothes\EQClothing\FlagsNBands\data\Flag_BRMercenarious.paa",
			"MassiveMod\NewClothes\EQClothing\FlagsNBands\data\Flag_BRMercenarious.paa"
		};
	};
	class flag_base;
	class flag_cmf: flag_base
	{
		scope=2;
		visibilityModifier=0.94999999;
		color="cmf";
		hiddenSelectionsTextures[]=
		{
			"MassiveMod\NewClothes\EQClothing\FlagsNBands\data\flag_white_co_cmf.paa",
			"MassiveMod\NewClothes\EQClothing\FlagsNBands\data\flag_white_co_cmf.paa",
			"MassiveMod\NewClothes\EQClothing\FlagsNBands\data\flag_white_co_cmf.paa",
			"MassiveMod\NewClothes\EQClothing\FlagsNBands\data\flag_white_co_cmf.paa",
			"MassiveMod\NewClothes\EQClothing\FlagsNBands\data\flag_white_co_cmf.paa",
			"MassiveMod\NewClothes\EQClothing\FlagsNBands\data\flag_white_co_cmf.paa",
			"MassiveMod\NewClothes\EQClothing\FlagsNBands\data\flag_white_co_cmf.paa",
			"MassiveMod\NewClothes\EQClothing\FlagsNBands\data\flag_white_co_cmf.paa",
			"MassiveMod\NewClothes\EQClothing\FlagsNBands\data\flag_white_co_cmf.paa"
		};
	};
	class flag_ncr: flag_base
	{
		scope=2;
		visibilityModifier=0.94999999;
		color="ncr";
		hiddenSelectionsTextures[]=
		{
			"MassiveMod\NewClothes\EQClothing\FlagsNBands\data\flag_white_co_ncr.paa",
			"MassiveMod\NewClothes\EQClothing\FlagsNBands\data\flag_white_co_ncr.paa",
			"MassiveMod\NewClothes\EQClothing\FlagsNBands\data\flag_white_co_ncr.paa",
			"MassiveMod\NewClothes\EQClothing\FlagsNBands\data\flag_white_co_ncr.paa",
			"MassiveMod\NewClothes\EQClothing\FlagsNBands\data\flag_white_co_ncr.paa",
			"MassiveMod\NewClothes\EQClothing\FlagsNBands\data\flag_white_co_ncr.paa",
			"MassiveMod\NewClothes\EQClothing\FlagsNBands\data\flag_white_co_ncr.paa",
			"MassiveMod\NewClothes\EQClothing\FlagsNBands\data\flag_white_co_ncr.paa",
			"MassiveMod\NewClothes\EQClothing\FlagsNBands\data\flag_white_co_ncr.paa"
		};
	};
	class flag_OOrder: flag_base
	{
		scope=2;
		visibilityModifier=0.94999999;
		color="OO";
		hiddenSelectionsTextures[]=
		{
			"MassiveMod\NewClothes\EQClothing\FlagsNBands\data\flag_white_co_OO.paa",
			"MassiveMod\NewClothes\EQClothing\FlagsNBands\data\flag_white_co_OO.paa",
			"MassiveMod\NewClothes\EQClothing\FlagsNBands\data\flag_white_co_OO.paa",
			"MassiveMod\NewClothes\EQClothing\FlagsNBands\data\flag_white_co_OO.paa",
			"MassiveMod\NewClothes\EQClothing\FlagsNBands\data\flag_white_co_OO.paa",
			"MassiveMod\NewClothes\EQClothing\FlagsNBands\data\flag_white_co_OO.paa",
			"MassiveMod\NewClothes\EQClothing\FlagsNBands\data\flag_white_co_OO.paa",
			"MassiveMod\NewClothes\EQClothing\FlagsNBands\data\flag_white_co_OO.paa",
			"MassiveMod\NewClothes\EQClothing\FlagsNBands\data\flag_white_co_OO.paa"
		};
	};
	class flag_GOK: flag_base
	{
		scope=2;
		visibilityModifier=0.94999999;
		color="ghosts";
		hiddenSelectionsTextures[]=
		{
			"MassiveMod\NewClothes\EQClothing\FlagsNBands\data\flag_white_co_ghosts.paa",
			"MassiveMod\NewClothes\EQClothing\FlagsNBands\data\flag_white_co_ghosts.paa",
			"MassiveMod\NewClothes\EQClothing\FlagsNBands\data\flag_white_co_ghosts.paa",
			"MassiveMod\NewClothes\EQClothing\FlagsNBands\data\flag_white_co_ghosts.paa",
			"MassiveMod\NewClothes\EQClothing\FlagsNBands\data\flag_white_co_ghosts.paa",
			"MassiveMod\NewClothes\EQClothing\FlagsNBands\data\flag_white_co_ghosts.paa",
			"MassiveMod\NewClothes\EQClothing\FlagsNBands\data\flag_white_co_ghosts.paa",
			"MassiveMod\NewClothes\EQClothing\FlagsNBands\data\flag_white_co_ghosts.paa",
			"MassiveMod\NewClothes\EQClothing\FlagsNBands\data\flag_white_co_ghosts.paa"
		};
	};
	class flag_TU: flag_base
	{
		scope=2;
		visibilityModifier=0.94999999;
		color="Trade";
		hiddenSelectionsTextures[]=
		{
			"MassiveMod\NewClothes\EQClothing\FlagsNBands\data\flag_TU_NEW.paa",
			"MassiveMod\NewClothes\EQClothing\FlagsNBands\data\flag_TU_NEW.paa",
			"MassiveMod\NewClothes\EQClothing\FlagsNBands\data\flag_TU_NEW.paa",
			"MassiveMod\NewClothes\EQClothing\FlagsNBands\data\flag_TU_NEW.paa",
			"MassiveMod\NewClothes\EQClothing\FlagsNBands\data\flag_TU_NEW.paa",
			"MassiveMod\NewClothes\EQClothing\FlagsNBands\data\flag_TU_NEW.paa",
			"MassiveMod\NewClothes\EQClothing\FlagsNBands\data\flag_TU_NEW.paa",
			"MassiveMod\NewClothes\EQClothing\FlagsNBands\data\flag_TU_NEW.paa",
			"MassiveMod\NewClothes\EQClothing\FlagsNBands\data\flag_TU_NEW.paa"
		};
	};
	class flag_Medic: flag_base
	{
		scope=2;
		visibilityModifier=0.94999999;
		color="medic";
		hiddenSelectionsTextures[]=
		{
			"MassiveMod\NewClothes\EQClothing\FlagsNBands\data\flag_white_co_medic_armband_large.paa",
			"MassiveMod\NewClothes\EQClothing\FlagsNBands\data\flag_white_co_medic_armband_large.paa",
			"MassiveMod\NewClothes\EQClothing\FlagsNBands\data\flag_white_co_medic_armband_large.paa",
			"MassiveMod\NewClothes\EQClothing\FlagsNBands\data\flag_white_co_medic_armband_large.paa",
			"MassiveMod\NewClothes\EQClothing\FlagsNBands\data\flag_white_co_medic_armband_large.paa",
			"MassiveMod\NewClothes\EQClothing\FlagsNBands\data\flag_white_co_medic_armband_large.paa",
			"MassiveMod\NewClothes\EQClothing\FlagsNBands\data\flag_white_co_medic_armband_large.paa",
			"MassiveMod\NewClothes\EQClothing\FlagsNBands\data\flag_white_co_medic_armband_large.paa",
			"MassiveMod\NewClothes\EQClothing\FlagsNBands\data\flag_white_co_medic_armband_large.paa"
		};
	};
	class flag_Medic_small: flag_base
	{
		scope=2;
		visibilityModifier=0.94999999;
		color="medic2";
		hiddenSelectionsTextures[]=
		{
			"MassiveMod\NewClothes\EQClothing\FlagsNBands\data\flag_white_co_medic_armband_small.paa",
			"MassiveMod\NewClothes\EQClothing\FlagsNBands\data\flag_white_co_medic_armband_small.paa",
			"MassiveMod\NewClothes\EQClothing\FlagsNBands\data\flag_white_co_medic_armband_small.paa",
			"MassiveMod\NewClothes\EQClothing\FlagsNBands\data\flag_white_co_medic_armband_small.paa",
			"MassiveMod\NewClothes\EQClothing\FlagsNBands\data\flag_white_co_medic_armband_small.paa",
			"MassiveMod\NewClothes\EQClothing\FlagsNBands\data\flag_white_co_medic_armband_small.paa",
			"MassiveMod\NewClothes\EQClothing\FlagsNBands\data\flag_white_co_medic_armband_small.paa",
			"MassiveMod\NewClothes\EQClothing\FlagsNBands\data\flag_white_co_medic_armband_small.paa",
			"MassiveMod\NewClothes\EQClothing\FlagsNBands\data\flag_white_co_medic_armband_small.paa"
		};
	};
	class flag_imperium: flag_base
	{
		scope=2;
		visibilityModifier=0.94999999;
		color="newimpR";
		hiddenSelectionsTextures[]=
		{
			"MassiveMod\NewClothes\EQClothing\FlagsNBands\data\Imperium_red.paa",
			"MassiveMod\NewClothes\EQClothing\FlagsNBands\data\Imperium_red.paa",
			"MassiveMod\NewClothes\EQClothing\FlagsNBands\data\Imperium_red.paa",
			"MassiveMod\NewClothes\EQClothing\FlagsNBands\data\Imperium_red.paa",
			"MassiveMod\NewClothes\EQClothing\FlagsNBands\data\Imperium_red.paa",
			"MassiveMod\NewClothes\EQClothing\FlagsNBands\data\Imperium_red.paa",
			"MassiveMod\NewClothes\EQClothing\FlagsNBands\data\Imperium_red.paa",
			"MassiveMod\NewClothes\EQClothing\FlagsNBands\data\Imperium_red.paa",
			"MassiveMod\NewClothes\EQClothing\FlagsNBands\data\Imperium_red.paa"
		};
	};
	class flag_Druzhina: flag_base
	{
		scope=2;
		visibilityModifier=0.94999999;
		color="druzhina";
		hiddenSelectionsTextures[]=
		{
			"MassiveMod\NewClothes\EQClothing\FlagsNBands\data\flag_white_co_druzhina.paa",
			"MassiveMod\NewClothes\EQClothing\FlagsNBands\data\flag_white_co_druzhina.paa",
			"MassiveMod\NewClothes\EQClothing\FlagsNBands\data\flag_white_co_druzhina.paa",
			"MassiveMod\NewClothes\EQClothing\FlagsNBands\data\flag_white_co_druzhina.paa",
			"MassiveMod\NewClothes\EQClothing\FlagsNBands\data\flag_white_co_druzhina.paa",
			"MassiveMod\NewClothes\EQClothing\FlagsNBands\data\flag_white_co_druzhina.paa",
			"MassiveMod\NewClothes\EQClothing\FlagsNBands\data\flag_white_co_druzhina.paa",
			"MassiveMod\NewClothes\EQClothing\FlagsNBands\data\flag_white_co_druzhina.paa",
			"MassiveMod\NewClothes\EQClothing\FlagsNBands\data\flag_white_co_druzhina.paa"
		};
	};
	class flag_end: flag_base
	{
		scope=2;
		visibilityModifier=0.94999999;
		color="end";
		hiddenSelectionsTextures[]=
		{
			"MassiveMod\NewClothes\EQClothing\FlagsNBands\data\flag_END2.paa",
			"MassiveMod\NewClothes\EQClothing\FlagsNBands\data\flag_END2.paa",
			"MassiveMod\NewClothes\EQClothing\FlagsNBands\data\flag_END2.paa",
			"MassiveMod\NewClothes\EQClothing\FlagsNBands\data\flag_END2.paa",
			"MassiveMod\NewClothes\EQClothing\FlagsNBands\data\flag_END2.paa",
			"MassiveMod\NewClothes\EQClothing\FlagsNBands\data\flag_END2.paa",
			"MassiveMod\NewClothes\EQClothing\FlagsNBands\data\flag_END2.paa",
			"MassiveMod\NewClothes\EQClothing\FlagsNBands\data\flag_END2.paa",
			"MassiveMod\NewClothes\EQClothing\FlagsNBands\data\flag_END2.paa"
		};
	};
	class flag_Northern_Republic: flag_base
	{
		scope=2;
		visibilityModifier=0.94999999;
		color="North Rep";
		hiddenSelectionsTextures[]=
		{
			"MassiveMod\NewClothes\EQClothing\FlagsNBands\data\flag_Northern_Republic.paa",
			"MassiveMod\NewClothes\EQClothing\FlagsNBands\data\flag_Northern_Republic.paa",
			"MassiveMod\NewClothes\EQClothing\FlagsNBands\data\flag_Northern_Republic.paa",
			"MassiveMod\NewClothes\EQClothing\FlagsNBands\data\flag_Northern_Republic.paa",
			"MassiveMod\NewClothes\EQClothing\FlagsNBands\data\flag_Northern_Republic.paa",
			"MassiveMod\NewClothes\EQClothing\FlagsNBands\data\flag_Northern_Republic.paa",
			"MassiveMod\NewClothes\EQClothing\FlagsNBands\data\flag_Northern_Republic.paa",
			"MassiveMod\NewClothes\EQClothing\FlagsNBands\data\flag_Northern_Republic.paa",
			"MassiveMod\NewClothes\EQClothing\FlagsNBands\data\flag_Northern_Republic.paa"
		};
	};
	class flag_ZenComm: flag_base
	{
		scope=2;
		visibilityModifier=0.94999999;
		color="ZenComm";
		hiddenSelectionsTextures[]=
		{
			"MassiveMod\NewClothes\EQClothing\FlagsNBands\data\flag_ZenComm.paa",
			"MassiveMod\NewClothes\EQClothing\FlagsNBands\data\flag_ZenComm.paa",
			"MassiveMod\NewClothes\EQClothing\FlagsNBands\data\flag_ZenComm.paa",
			"MassiveMod\NewClothes\EQClothing\FlagsNBands\data\flag_ZenComm.paa",
			"MassiveMod\NewClothes\EQClothing\FlagsNBands\data\flag_ZenComm.paa",
			"MassiveMod\NewClothes\EQClothing\FlagsNBands\data\flag_ZenComm.paa",
			"MassiveMod\NewClothes\EQClothing\FlagsNBands\data\flag_ZenComm.paa",
			"MassiveMod\NewClothes\EQClothing\FlagsNBands\data\flag_ZenComm.paa",
			"MassiveMod\NewClothes\EQClothing\FlagsNBands\data\flag_ZenComm.paa"
		};
	};
	class flag_Eclipse: flag_base
	{
		scope=2;
		visibilityModifier=0.94999999;
		color="Eclipse";
		hiddenSelectionsTextures[]=
		{
			"MassiveMod\NewClothes\EQClothing\FlagsNBands\data\Eclipse_flag.paa",
			"MassiveMod\NewClothes\EQClothing\FlagsNBands\data\Eclipse_flag.paa",
			"MassiveMod\NewClothes\EQClothing\FlagsNBands\data\Eclipse_flag.paa",
			"MassiveMod\NewClothes\EQClothing\FlagsNBands\data\Eclipse_flag.paa",
			"MassiveMod\NewClothes\EQClothing\FlagsNBands\data\Eclipse_flag.paa",
			"MassiveMod\NewClothes\EQClothing\FlagsNBands\data\Eclipse_flag.paa",
			"MassiveMod\NewClothes\EQClothing\FlagsNBands\data\Eclipse_flag.paa",
			"MassiveMod\NewClothes\EQClothing\FlagsNBands\data\Eclipse_flag.paa",
			"MassiveMod\NewClothes\EQClothing\FlagsNBands\data\Eclipse_flag.paa"
		};
	};
	class flag_Blackwater: flag_base
	{
		scope=2;
		visibilityModifier=0.94999999;
		color="Blackwater";
		hiddenSelectionsTextures[]=
		{
			"MassiveMod\NewClothes\EQClothing\FlagsNBands\data\Blackwater_flag.paa",
			"MassiveMod\NewClothes\EQClothing\FlagsNBands\data\Blackwater_flag.paa",
			"MassiveMod\NewClothes\EQClothing\FlagsNBands\data\Blackwater_flag.paa",
			"MassiveMod\NewClothes\EQClothing\FlagsNBands\data\Blackwater_flag.paa",
			"MassiveMod\NewClothes\EQClothing\FlagsNBands\data\Blackwater_flag.paa",
			"MassiveMod\NewClothes\EQClothing\FlagsNBands\data\Blackwater_flag.paa",
			"MassiveMod\NewClothes\EQClothing\FlagsNBands\data\Blackwater_flag.paa",
			"MassiveMod\NewClothes\EQClothing\FlagsNBands\data\Blackwater_flag.paa",
			"MassiveMod\NewClothes\EQClothing\FlagsNBands\data\Blackwater_flag.paa"
		};
	};
	class flag_Jackal: flag_base
	{
		scope=2;
		visibilityModifier=0.94999999;
		color="Jackal";
		hiddenSelectionsTextures[]=
		{
			"MassiveMod\NewClothes\EQClothing\FlagsNBands\data\Jackals_flags.paa",
			"MassiveMod\NewClothes\EQClothing\FlagsNBands\data\Jackals_flags.paa",
			"MassiveMod\NewClothes\EQClothing\FlagsNBands\data\Jackals_flags.paa",
			"MassiveMod\NewClothes\EQClothing\FlagsNBands\data\Jackals_flags.paa",
			"MassiveMod\NewClothes\EQClothing\FlagsNBands\data\Jackals_flags.paa",
			"MassiveMod\NewClothes\EQClothing\FlagsNBands\data\Jackals_flags.paa",
			"MassiveMod\NewClothes\EQClothing\FlagsNBands\data\Jackals_flags.paa",
			"MassiveMod\NewClothes\EQClothing\FlagsNBands\data\Jackals_flags.paa",
			"MassiveMod\NewClothes\EQClothing\FlagsNBands\data\Jackals_flags.paa"
		};
	};
	class flag_KJ: flag_base
	{
		scope=2;
		visibilityModifier=0.94999999;
		color="pickle";
		hiddenSelectionsTextures[]=
		{
			"MassiveMod\NewClothes\EQClothing\FlagsNBands\data\flag_KJ.paa",
			"MassiveMod\NewClothes\EQClothing\FlagsNBands\data\flag_KJ.paa",
			"MassiveMod\NewClothes\EQClothing\FlagsNBands\data\flag_KJ.paa",
			"MassiveMod\NewClothes\EQClothing\FlagsNBands\data\flag_KJ.paa",
			"MassiveMod\NewClothes\EQClothing\FlagsNBands\data\flag_KJ.paa",
			"MassiveMod\NewClothes\EQClothing\FlagsNBands\data\flag_KJ.paa",
			"MassiveMod\NewClothes\EQClothing\FlagsNBands\data\flag_KJ.paa",
			"MassiveMod\NewClothes\EQClothing\FlagsNBands\data\flag_KJ.paa",
			"MassiveMod\NewClothes\EQClothing\FlagsNBands\data\flag_KJ.paa"
		};
	};
	class flag_BPirate: flag_base
	{
		scope=2;
		visibilityModifier=0.94999999;
		color="BPirate";
		hiddenSelectionsTextures[]=
		{
			"MassiveMod\NewClothes\EQClothing\FlagsNBands\data\flag_BPirate.paa",
			"MassiveMod\NewClothes\EQClothing\FlagsNBands\data\flag_BPirate.paa",
			"MassiveMod\NewClothes\EQClothing\FlagsNBands\data\flag_BPirate.paa",
			"MassiveMod\NewClothes\EQClothing\FlagsNBands\data\flag_BPirate.paa",
			"MassiveMod\NewClothes\EQClothing\FlagsNBands\data\flag_BPirate.paa",
			"MassiveMod\NewClothes\EQClothing\FlagsNBands\data\flag_BPirate.paa",
			"MassiveMod\NewClothes\EQClothing\FlagsNBands\data\flag_BPirate.paa",
			"MassiveMod\NewClothes\EQClothing\FlagsNBands\data\flag_BPirate.paa",
			"MassiveMod\NewClothes\EQClothing\FlagsNBands\data\flag_BPirate.paa"
		};
	};
	class flag_RoughRiders: flag_base
	{
		scope=2;
		visibilityModifier=0.94999999;
		color="RoughRiders";
		hiddenSelectionsTextures[]=
		{
			"MassiveMod\NewClothes\EQClothing\FlagsNBands\data\Rough_Riders_flag.paa",
			"MassiveMod\NewClothes\EQClothing\FlagsNBands\data\Rough_Riders_flag.paa",
			"MassiveMod\NewClothes\EQClothing\FlagsNBands\data\Rough_Riders_flag.paa",
			"MassiveMod\NewClothes\EQClothing\FlagsNBands\data\Rough_Riders_flag.paa",
			"MassiveMod\NewClothes\EQClothing\FlagsNBands\data\Rough_Riders_flag.paa",
			"MassiveMod\NewClothes\EQClothing\FlagsNBands\data\Rough_Riders_flag.paa",
			"MassiveMod\NewClothes\EQClothing\FlagsNBands\data\Rough_Riders_flag.paa",
			"MassiveMod\NewClothes\EQClothing\FlagsNBands\data\Rough_Riders_flag.paa",
			"MassiveMod\NewClothes\EQClothing\FlagsNBands\data\Rough_Riders_flag.paa"
		};
	};
	class flag_NRPS: flag_base
	{
		scope=2;
		visibilityModifier=0.94999999;
		color="Purple Sage";
		hiddenSelectionsTextures[]=
		{
			"MassiveMod\NewClothes\EQClothing\FlagsNBands\data\NRPS_flag.paa",
			"MassiveMod\NewClothes\EQClothing\FlagsNBands\data\NRPS_flag.paa",
			"MassiveMod\NewClothes\EQClothing\FlagsNBands\data\NRPS_flag.paa",
			"MassiveMod\NewClothes\EQClothing\FlagsNBands\data\NRPS_flag.paa",
			"MassiveMod\NewClothes\EQClothing\FlagsNBands\data\NRPS_flag.paa",
			"MassiveMod\NewClothes\EQClothing\FlagsNBands\data\NRPS_flag.paa",
			"MassiveMod\NewClothes\EQClothing\FlagsNBands\data\NRPS_flag.paa",
			"MassiveMod\NewClothes\EQClothing\FlagsNBands\data\NRPS_flag.paa",
			"MassiveMod\NewClothes\EQClothing\FlagsNBands\data\NRPS_flag.paa"
		};
	};
	class flag_Renegades: flag_base
	{
		scope=2;
		visibilityModifier=0.94999999;
		color="Renegades";
		hiddenSelectionsTextures[]=
		{
			"MassiveMod\NewClothes\EQClothing\FlagsNBands\data\Renegades_flag.paa",
			"MassiveMod\NewClothes\EQClothing\FlagsNBands\data\Renegades_flag.paa",
			"MassiveMod\NewClothes\EQClothing\FlagsNBands\data\Renegades_flag.paa",
			"MassiveMod\NewClothes\EQClothing\FlagsNBands\data\Renegades_flag.paa",
			"MassiveMod\NewClothes\EQClothing\FlagsNBands\data\Renegades_flag.paa",
			"MassiveMod\NewClothes\EQClothing\FlagsNBands\data\Renegades_flag.paa",
			"MassiveMod\NewClothes\EQClothing\FlagsNBands\data\Renegades_flag.paa",
			"MassiveMod\NewClothes\EQClothing\FlagsNBands\data\Renegades_flag.paa",
			"MassiveMod\NewClothes\EQClothing\FlagsNBands\data\Renegades_flag.paa"
		};
	};
	class flag_SCCollective: flag_base
	{
		scope=2;
		visibilityModifier=0.94999999;
		color="Collective";
		hiddenSelectionsTextures[]=
		{
			"MassiveMod\NewClothes\EQClothing\FlagsNBands\data\SCCollective_flag.paa",
			"MassiveMod\NewClothes\EQClothing\FlagsNBands\data\SCCollective_flag.paa",
			"MassiveMod\NewClothes\EQClothing\FlagsNBands\data\SCCollective_flag.paa",
			"MassiveMod\NewClothes\EQClothing\FlagsNBands\data\SCCollective_flag.paa",
			"MassiveMod\NewClothes\EQClothing\FlagsNBands\data\SCCollective_flag.paa",
			"MassiveMod\NewClothes\EQClothing\FlagsNBands\data\SCCollective_flag.paa",
			"MassiveMod\NewClothes\EQClothing\FlagsNBands\data\SCCollective_flag.paa",
			"MassiveMod\NewClothes\EQClothing\FlagsNBands\data\SCCollective_flag.paa",
			"MassiveMod\NewClothes\EQClothing\FlagsNBands\data\SCCollective_flag.paa"
		};
	};
	class flag_Afirma: flag_base
	{
		scope=2;
		visibilityModifier=0.94999999;
		color="Afirma";
		hiddenSelectionsTextures[]=
		{
			"MassiveMod\NewClothes\EQClothing\FlagsNBands\data\afirma_flag.paa",
			"MassiveMod\NewClothes\EQClothing\FlagsNBands\data\afirma_flag.paa",
			"MassiveMod\NewClothes\EQClothing\FlagsNBands\data\afirma_flag.paa",
			"MassiveMod\NewClothes\EQClothing\FlagsNBands\data\afirma_flag.paa",
			"MassiveMod\NewClothes\EQClothing\FlagsNBands\data\afirma_flag.paa",
			"MassiveMod\NewClothes\EQClothing\FlagsNBands\data\afirma_flag.paa",
			"MassiveMod\NewClothes\EQClothing\FlagsNBands\data\afirma_flag.paa",
			"MassiveMod\NewClothes\EQClothing\FlagsNBands\data\afirma_flag.paa",
			"MassiveMod\NewClothes\EQClothing\FlagsNBands\data\afirma_flag.paa"
		};
	};
	class flag_GOK2: flag_base
	{
		scope=2;
		visibilityModifier=0.94999999;
		color="GOK New";
		hiddenSelectionsTextures[]=
		{
			"MassiveMod\NewClothes\EQClothing\FlagsNBands\data\GoK2_flag.paa",
			"MassiveMod\NewClothes\EQClothing\FlagsNBands\data\GoK2_flag.paa",
			"MassiveMod\NewClothes\EQClothing\FlagsNBands\data\GoK2_flag.paa",
			"MassiveMod\NewClothes\EQClothing\FlagsNBands\data\GoK2_flag.paa",
			"MassiveMod\NewClothes\EQClothing\FlagsNBands\data\GoK2_flag.paa",
			"MassiveMod\NewClothes\EQClothing\FlagsNBands\data\GoK2_flag.paa",
			"MassiveMod\NewClothes\EQClothing\FlagsNBands\data\GoK2_flag.paa",
			"MassiveMod\NewClothes\EQClothing\FlagsNBands\data\GoK2_flag.paa",
			"MassiveMod\NewClothes\EQClothing\FlagsNBands\data\GoK2_flag.paa"
		};
	};
	class flag_JusticeLeague: flag_base
	{
		scope=2;
		visibilityModifier=0.94999999;
		color="Justice League";
		hiddenSelectionsTextures[]=
		{
			"MassiveMod\NewClothes\EQClothing\FlagsNBands\data\JusticeLeague_flag.paa",
			"MassiveMod\NewClothes\EQClothing\FlagsNBands\data\JusticeLeague_flag.paa",
			"MassiveMod\NewClothes\EQClothing\FlagsNBands\data\JusticeLeague_flag.paa",
			"MassiveMod\NewClothes\EQClothing\FlagsNBands\data\JusticeLeague_flag.paa",
			"MassiveMod\NewClothes\EQClothing\FlagsNBands\data\JusticeLeague_flag.paa",
			"MassiveMod\NewClothes\EQClothing\FlagsNBands\data\JusticeLeague_flag.paa",
			"MassiveMod\NewClothes\EQClothing\FlagsNBands\data\JusticeLeague_flag.paa",
			"MassiveMod\NewClothes\EQClothing\FlagsNBands\data\JusticeLeague_flag.paa",
			"MassiveMod\NewClothes\EQClothing\FlagsNBands\data\JusticeLeague_flag.paa"
		};
	};
	class flag_Mogilevka: flag_base
	{
		scope=2;
		visibilityModifier=0.94999999;
		color="Mogilevka";
		hiddenSelectionsTextures[]=
		{
			"MassiveMod\NewClothes\EQClothing\FlagsNBands\data\Mogilevka_flag.paa",
			"MassiveMod\NewClothes\EQClothing\FlagsNBands\data\Mogilevka_flag.paa",
			"MassiveMod\NewClothes\EQClothing\FlagsNBands\data\Mogilevka_flag.paa",
			"MassiveMod\NewClothes\EQClothing\FlagsNBands\data\Mogilevka_flag.paa",
			"MassiveMod\NewClothes\EQClothing\FlagsNBands\data\Mogilevka_flag.paa",
			"MassiveMod\NewClothes\EQClothing\FlagsNBands\data\Mogilevka_flag.paa",
			"MassiveMod\NewClothes\EQClothing\FlagsNBands\data\Mogilevka_flag.paa",
			"MassiveMod\NewClothes\EQClothing\FlagsNBands\data\Mogilevka_flag.paa",
			"MassiveMod\NewClothes\EQClothing\FlagsNBands\data\Mogilevka_flag.paa"
		};
	};
	class flag_Blackwater2: flag_Base
	{
		scope=2;
		visibilityModifier=0.94999999;
		color="Blackwater";
		hiddenSelectionsTextures[]=
		{
			"MassiveMod\NewClothes\EQClothing\FlagsNBands\data\Blackwater2_flag.paa",
			"MassiveMod\NewClothes\EQClothing\FlagsNBands\data\Blackwater2_flag.paa",
			"MassiveMod\NewClothes\EQClothing\FlagsNBands\data\Blackwater2_flag.paa",
			"MassiveMod\NewClothes\EQClothing\FlagsNBands\data\Blackwater2_flag.paa",
			"MassiveMod\NewClothes\EQClothing\FlagsNBands\data\Blackwater2_flag.paa",
			"MassiveMod\NewClothes\EQClothing\FlagsNBands\data\Blackwater2_flag.paa",
			"MassiveMod\NewClothes\EQClothing\FlagsNBands\data\Blackwater2_flag.paa",
			"MassiveMod\NewClothes\EQClothing\FlagsNBands\data\Blackwater2_flag.paa",
			"MassiveMod\NewClothes\EQClothing\FlagsNBands\data\Blackwater2_flag.paa"
		};
	};
	class Flag_TBT: flag_Base
	{
		scope=2;
		visibilityModifier=0.94999999;
		color="TBT";
		hiddenSelectionsTextures[]=
		{
			"MassiveMod\NewClothes\EQClothing\FlagsNBands\data\Flag_TBT.paa",
			"MassiveMod\NewClothes\EQClothing\FlagsNBands\data\Flag_TBT.paa",
			"MassiveMod\NewClothes\EQClothing\FlagsNBands\data\Flag_TBT.paa",
			"MassiveMod\NewClothes\EQClothing\FlagsNBands\data\Flag_TBT.paa",
			"MassiveMod\NewClothes\EQClothing\FlagsNBands\data\Flag_TBT.paa",
			"MassiveMod\NewClothes\EQClothing\FlagsNBands\data\Flag_TBT.paa",
			"MassiveMod\NewClothes\EQClothing\FlagsNBands\data\Flag_TBT.paa",
			"MassiveMod\NewClothes\EQClothing\FlagsNBands\data\Flag_TBT.paa",
			"MassiveMod\NewClothes\EQClothing\FlagsNBands\data\Flag_TBT.paa"
		};
	};
	class Flag_BRMercenarious: flag_Base
	{
		scope=2;
		visibilityModifier=0.94999999;
		color="BRMercenarious";
		hiddenSelectionsTextures[]=
		{
			"MassiveMod\NewClothes\EQClothing\FlagsNBands\data\Flag_BRMercenarious.paa",
			"MassiveMod\NewClothes\EQClothing\FlagsNBands\data\Flag_BRMercenarious.paa",
			"MassiveMod\NewClothes\EQClothing\FlagsNBands\data\Flag_BRMercenarious.paa",
			"MassiveMod\NewClothes\EQClothing\FlagsNBands\data\Flag_BRMercenarious.paa",
			"MassiveMod\NewClothes\EQClothing\FlagsNBands\data\Flag_BRMercenarious.paa",
			"MassiveMod\NewClothes\EQClothing\FlagsNBands\data\Flag_BRMercenarious.paa",
			"MassiveMod\NewClothes\EQClothing\FlagsNBands\data\Flag_BRMercenarious.paa",
			"MassiveMod\NewClothes\EQClothing\FlagsNBands\data\Flag_BRMercenarious.paa",
			"MassiveMod\NewClothes\EQClothing\FlagsNBands\data\Flag_BRMercenarious.paa"
		};
	};
};
