//LMGs
class A6_Mag_FNEvolys_100Rnd: MagazineStorage {}
class A6_Mag_M249_200Rnd: MagazineStorage {}
class A6_Mag_PKM_100Rnd: MagazineStorage {}
class A6_Mag_RPK_75Rnd: MagazineStorage {}
class A6_Mag_M60E4_100Rnd: MagazineStorage {}
//Pistols
class A6_Mag_RugerMarkIV_10Rnd: MagazineStorage {}
class A6_Mag_Glock19_15Rnd: MagazineStorage {}
class A6_Mag_M1911_Compact_9Rnd: MagazineStorage {}
class A6_Mag_M1911_7Rnd: MagazineStorage {}
class A6_Mag_DesertEagle_9Rnd: MagazineStorage {}
class A6_Mag_FiveSeven_20Rnd: MagazineStorage {}
class A6_Mag_M9_15Rnd: MagazineStorage {}
class A6_Mag_PX4_14Rnd: MagazineStorage {}
class A6_Mag_MPShield_13Rnd: MagazineStorage {}
class A6_Mag_MP9Pro_17Rnd: MagazineStorage {}
class A6_Mag_P320_17Rnd: MagazineStorage {}
class A6_Mag_P320_Tan_17Rnd: MagazineStorage {}
//Rifles
class A6_Mag_XM8_100Rnd: MagazineStorage {}
class A6_Mag_HKG28_20Rnd: MagazineStorage {}
class A6_Mag_HK_PMG2_30Rnd: MagazineStorage {}
class A6_Mag_M14_10Rnd: MagazineStorage {}
class A6_Mag_M14_20Rnd: MagazineStorage {}
class A6_Mag_AK101_30Rnd: MagazineStorage {}
class A6_Mag_OPSKS_20Rnd: MagazineStorage {}
class A6_Mag_Famas_25Rnd: MagazineStorage {}
class A6_Mag_VSS_10Rnd: MagazineStorage {}
class A6_Mag_VSS_Red_10Rnd: MagazineStorage {}
class A6_Mag_VAL_20Rnd: MagazineStorage {}
class A6_Mag_VAL_Red_20Rnd: MagazineStorage {}
class A6_Mag_Vikhr_30Rnd: MagazineStorage {}
class A6_Mag_SR3_30Rnd: MagazineStorage {}
class A6_Mag_SR3_Red_30Rnd: MagazineStorage {}
class A6_Mag_Aug_30Rnd: MagazineStorage {}
class A6_Mag_Aug_Black_30Rnd: MagazineStorage {}
class A6_Mag_FAL_20Rnd: MagazineStorage {}
class A6_Mag_FAL_30Rnd: MagazineStorage {}
class A6_Mag_FAL_50Rnd: MagazineStorage {}
class A6_Mag_ASH12_10Rnd: MagazineStorage {}
class A6_Mag_ASH12_20Rnd: MagazineStorage {}
class A6_Mag_Beowulf_10Rnd: MagazineStorage {}
class A6_Mag_300BLK_PMAG_20Rnd: MagazineStorage {}
class A6_Mag_300BLK_PMAG_30Rnd: MagazineStorage {}
class A6_Mag_556_PMAG_20Rnd: MagazineStorage {}
class A6_Mag_556_PMAG_30Rnd: MagazineStorage {}
class A6_Mag_556_PMAG_60Rnd: MagazineStorage {}
class A6_Mag_300BLK_PMAG_60Rnd: MagazineStorage {}
class A6_Mag_308_Stanag_20Rnd: MagazineStorage {}
class A6_Mag_308_PMAG_20Rnd: MagazineStorage {}
class A6_Mag_SCARH_20Rnd: MagazineStorage {}
class A6_Mag_SCARH_Tan_20Rnd: MagazineStorage {}
class A6_Mag_68_SPC_30Rnd: MagazineStorage {}
class A6_Mag_MCX_Spear_20Rnd: MagazineStorage {}
class A6_Mag_AK74_30Rnd: MagazineStorage {}
class A6_Mag_AK74_Orange_30Rnd: MagazineStorage {}
class A6_Mag_AKM_Poly_30Rnd: MagazineStorage {}
class A6_Mag_AKM_30Rnd: MagazineStorage {}
class A6_Mag_AKM_PMAG_30Rnd: MagazineStorage {}
class A6_Mag_Stanag_20Rnd: MagazineStorage {}
class A6_Mag_Stanag_30Rnd: MagazineStorage {}
class A6_Mag_Stanag_60Rnd: MagazineStorage {}
class A6_Mag_AK74_60Rnd: MagazineStorage {}
//Shotguns
class A6_Mag_AA12_24Rnd: MagazineStorage {}
//SMGs
class A6_Mag_PP19Bizon_64Rnd: MagazineStorage {}
class A6_Mag_Gripped_PP19Bizon_64Rnd: MagazineStorage {}
class A6_Mag_MP5_15Rnd: MagazineStorage {}
class A6_Mag_MP5_30Rnd: MagazineStorage {}
class A6_Mag_MP5_Waffle_30Rnd: MagazineStorage {}
class A6_Mag_MP5_100Rnd: MagazineStorage {}
class A6_Mag_UMP45_25Rnd: MagazineStorage {}
class A6_Mag_AugPara_32Rnd: MagazineStorage {}
class A6_Mag_PP19_30Rnd: MagazineStorage {}
class A6_Mag_Vector_33Rnd: MagazineStorage {}
class A6_Mag_Vector_50Rnd: MagazineStorage {}
class A6_Mag_MP7A2_20Rnd: MagazineStorage {}
class A6_Mag_MP7A2_40Rnd: MagazineStorage {}
class A6_Mag_P90_50Rnd: MagazineStorage {}
class A6_Mag_Scorpion_Evo_30Rnd: MagazineStorage {}
class A6_Mag_Scorpion_Evo_40Rnd: MagazineStorage {}
class A6_Mag_9A91_20Rnd: MagazineStorage {}
class A6_Mag_AK74_45Rnd: MagazineStorage {}
class A6_Mag_AK74_Orange_45Rnd: MagazineStorage {}
//Snipers
class A6_Mag_SV98_10Rnd: MagazineStorage {}
class A6_Mag_MK18_Mjolnir_10Rnd: MagazineStorage {}
class A6_Mag_Delta5_10Rnd: MagazineStorage {}
class A6_Mag_T5000_5Rnd: MagazineStorage {}
class A6_Mag_GM6Lynx_5Rnd: MagazineStorage {}
class A6_Mag_AWM_5Rnd: MagazineStorage {}
class A6_Mag_M82_10Rnd: MagazineStorage {}
class A6_Mag_AX_7Rnd: MagazineStorage {}
class A6_Mag_M200_7Rnd: MagazineStorage {}
class A6_Mag_M200_Tan_7Rnd: MagazineStorage {}
class A6_Mag_M24_5Rnd: MagazineStorage {}
class A6_Mag_AX50_5Rnd: MagazineStorage {}
class A6_Mag_VSSK_5Rnd: MagazineStorage {}
class A6_Mag_SRSA2_8Rnd: MagazineStorage {}
class A6_Mag_R700_5Rnd: MagazineStorage {}
class A6_Mag_TheFix_10Rnd: MagazineStorage {}
class A6_Mag_DVL10_5Rnd: MagazineStorage {}
class A6_Mag_SVD_10Rnd: MagazineStorage {}
class A6_Mag_SVD_20Rnd: MagazineStorage {}
class A6_Mag_Alligator_Snipex_5Rnd: MagazineStorage {}