class A6_M4A1_PistolGrip_Base : A6_PistolGrip_Base {}
class A6_M4A1_PistolGrip_Hogue : A6_M4A1_PistolGrip_Base {}
class A6_M4A1_PistolGrip_Hogue_Forest : A6_M4A1_PistolGrip_Base {}
class A6_M4A1_PistolGrip_Hogue_Desert : A6_M4A1_PistolGrip_Base {}
class A6_M4A1_PistolGrip_Gevar : A6_M4A1_PistolGrip_Base {}
class A6_M4A1_PistolGrip_Gevar_Tan : A6_M4A1_PistolGrip_Base {}
class A6_M4A1_PistolGrip_DD : A6_M4A1_PistolGrip_Base {}
class A6_M4A1_PistolGrip_DD_Tan : A6_M4A1_PistolGrip_Base {}
class A6_M4A1_PistolGrip_Skeleton : A6_M4A1_PistolGrip_Base {}
class A6_M4A1_PistolGrip_Skeleton_Black : A6_M4A1_PistolGrip_Base {}
class A6_M4A1_PistolGrip_Skeleton_Red : A6_M4A1_PistolGrip_Base {}
class A6_M4A1_PistolGrip_MOE : A6_M4A1_PistolGrip_Base {}
class A6_M4A1_PistolGrip_MOE_Green : A6_M4A1_PistolGrip_Base {}
class A6_M4A1_PistolGrip_MOE_Tan : A6_M4A1_PistolGrip_Base {}
class A6_M4A1_PistolGrip_Ergo : A6_M4A1_PistolGrip_Base {}
class A6_HK_PistolGrip_BG_Black : A6_M4A1_PistolGrip_Base {}
class A6_HK_PistolGrip_BG_Tan : A6_M4A1_PistolGrip_Base {}
class A6_HK_PistolGrip_BG_Green : A6_M4A1_PistolGrip_Base {}
class A6_HK_PistolGrip_BGB_Black : A6_M4A1_PistolGrip_Base {}
class A6_HK_PistolGrip_BGB_Tan : A6_M4A1_PistolGrip_Base {}
class A6_HK_PistolGrip_BGB_Green : A6_M4A1_PistolGrip_Base {}
class A6_M4A1_PistolGrip_F1 : A6_M4A1_PistolGrip_Base {}
class A6_M4A1_PistolGrip_F1_Tan : A6_M4A1_PistolGrip_F1 {}
class A6_M4A1_PistolGrip_F1_Green : A6_M4A1_PistolGrip_F1 {}
class A6_M4A1_PistolGrip_F1_Red : A6_M4A1_PistolGrip_F1 {}