class A6_ItemOptics extends ItemOptics {}
class A6_SigSauerRomeo0_Optic : A6_ItemOptics {}
class A6_SigSauerRomeo2_Optic_Base : A6_ItemOptics {}
class A6_SigSauerRomeo2_Optic : A6_SigSauerRomeo2_Optic_Base {}
class A6_SigSauerRomeo2_Optic_Tan : A6_SigSauerRomeo2_Optic_Base {}
class A6_SigSauerRomeo2_Optic_MRDMount_Base : A6_ItemOptics {}
class A6_SigSauerRomeo2_Optic_MRDMount : A6_SigSauerRomeo2_Optic_MRDMount_Base {}
class A6_SigSauerRomeo2_Optic_Tan_MRDMount : A6_SigSauerRomeo2_Optic_MRDMount_Base {}
class A6_RMROptic_Base : A6_ItemOptics {}
class A6_RMROptic_Black : A6_RMROptic_Base {}
class A6_RMROptic_Tan : A6_RMROptic_Base {}
class A6_RMROptic_MRDMount_Base : A6_ItemOptics {}
class A6_RMROptic_Black_MRDMount : A6_RMROptic_MRDMount_Base {}
class A6_RMROptic_Tan_MRDMount : A6_RMROptic_MRDMount_Base {}
class A6_AcogOptic_Base : A6_ItemOptics {}
class A6_AcogOptic_Black : A6_AcogOptic_Base {}
class A6_AcogOptic_Tan : A6_AcogOptic_Base {}
class A6_AcogOptic_RMROptic_Base : A6_ItemOptics {}
class A6_AcogOptic_Black_RMROptic_Black : A6_AcogOptic_RMROptic_Base {}
class A6_AcogOptic_Black_RMROptic_Tan : A6_AcogOptic_RMROptic_Base {}
class A6_AcogOptic_Tan_RMROptic_Tan : A6_AcogOptic_RMROptic_Base {}
class A6_AcogOptic_Tan_RMROptic_Black : A6_AcogOptic_RMROptic_Base {}
class A6_AcogOptic_SigSauerRomeo2_Optic_Base : A6_ItemOptics {}
class A6_AcogOptic_Black_SigSauerRomeo2_Optic : A6_AcogOptic_SigSauerRomeo2_Optic_Base {}
class A6_AcogOptic_Black_SigSauerRomeo2_Optic_Tan : A6_AcogOptic_SigSauerRomeo2_Optic_Base {}
class A6_AcogOptic_Tan_SigSauerRomeo2_Optic_Tan : A6_AcogOptic_SigSauerRomeo2_Optic_Base {}
class A6_AcogOptic_Tan_SigSauerRomeo2_Optic : A6_AcogOptic_SigSauerRomeo2_Optic_Base {}
class A6_SigSauerBravo4Optic : A6_ItemOptics {}
class A6_SigSauerBravo4Optic_RMROptic_Black_MRDMount : A6_SigSauerBravo4Optic {}
class A6_SigSauerBravo4Optic_RMROptic_Tan_MRDMount : A6_SigSauerBravo4Optic {}
class A6_SigSauerBravo4Optic_SigSauerRomeo2_Optic_MRDMount : A6_SigSauerBravo4Optic {}
class A6_SigSauerBravo4Optic_SigSauerRomeo2_Optic_Tan_MRDMount : A6_SigSauerBravo4Optic {}
class A6_SigSauerBravo4Optic_SigSauerRomeo0_Optic : A6_ItemOptics {}
class A6_AimpointCompM4Optic : A6_ItemOptics {}
class A6_EoTechHWS512_Optic : A6_ItemOptics {}
class A6_ElcanSpecterOptic : A6_ItemOptics {}
class A6_ElcanSpecterOptic_Tan: A6_ElcanSpecterOptic{}
class A6_HAMR_Optic : A6_ItemOptics {}
class A6_LeupoldMark6Optic : A6_ItemOptics {}
class A6_XTRI_Optic : A6_ItemOptics {}
class A6_VortexRazorOptic : A6_ItemOptics {}
class A6_VortexRazorOptic_Tan : A6_VortexRazorOptic {}
class A6_VortexRazorGenIIOptic : A6_ItemOptics {}
class A6_VuduOptic : A6_ItemOptics {}
class A6_SigSauerTango6T_Optic : A6_ItemOptics {}
class A6_SigSauerTango6T_Optic_Tan : A6_SigSauerTango6T_Optic {}